# General Issues in Clinical Assessment {#clinical}

## Historical Perspectives on Clinical Assessment

Historically, assessment has played a key role in clinical psychology. Many would consider assessment—especially the assessment of intelligence—the beginning of clinical psychology, and the role that distinguished clinical psychology from other fields. Intelligence testing has been one of the real successes of clinical psychology and assessment. For example, several early measures were developed to assess intelligence, including Cattell's measure and the Binet-Simon Intelligence scale. Lewis Terman at Stanford extended the Binet-Simon Intelligence scale to study gifted people, which became known as the Stanford-Binet.

During World War I, instruments were used to select people for various military occupations (e.g., pilot versus submariner). Intellectual assessment, including the Army Alpha and Beta tests, was used to decide who was psychologically unfit to serve. Then came the development of personality assessments, such as assessment of "shell shock," which would eventually become known as post-traumatic stress disorder (PTSD). The miliary conducted personality assessments to identify people who would be susceptible to shell shock, which would today be labeled a measure of "Neuroticism."

Intellectual assessment and personality assessment became the two principal tools for clinical psychologists. Initially, psychologists were primarily psychometricians. They developed assessment devices and helped score and interpret them. Initially, clinical psychologists did not play a large role in making diagnoses or in treatment—instead, psychiatrists did. However, that changed after World War I. Between World War I and World War II, assessment was the dominant role of practicing clinical psychologists, especially projective personality testing—such as word-association tests, Rorschach inkblot test, Thematic Apperception Test—and more objective personality testing. The Rorschach (1921) gave clinical psychologists a "voice at the table" with psychiatrists, even though doubts arose about its accuracy. Projective testing dominated personality assessment through the 1940s. The Minnesota Multiphasic Personality Inventory (MMPI), which became a popular objective personality test, was published in 1943.

During World War II, many of the modern psychology departments, clinical psychology programs, and VA-funded clinical psychology internships were created, not by the psychology community, but by the federal government to address wartime and post-wartime needs. Likewise, many measures were developed as a need to meet wartime needs. One of the origins of the psychometric movement in psychology was spurred by historical pressures to create tests to classify people during wartime, such as with the Army Alpha and Beta tests.

## Contemporary Trends

There has been a general decline in clinical assessment (and psychotherapy) by clinical psychologists. Assessment and measurement are crucial to research but are declining in treatment. This is in great part due to managed care, in which a primary goal is cost containment of mental health services. Managed care has resulted in greatly reduced patient access to mental health services, a dramatic reduction in insurance funds for reimbursement of services, more clinician time spent on paperwork and less time seeing clients, having less time for assessment because fewer sessions are reimbursed, tendencies to administer less frequent or less comprehensive assessments, and increased provision of psychological services from Master's-level providers because they are less expensive than doctoral providers.

Nevertheless, there are contexts in which clinical assessment is more common. There is still considerable assessment in the Department of Veterans Affairs (VA) system, including lots of testing and integrated reports. In addition to the VA, there is still considerable neuropsychological and aptitude testing. What is the future of assessment for treatment? My hope is that it will be evidence-based assessment (along with evidence-based treatment).

## Terminology

Several terms are relevant for clinical assessment. *Prevalence* is the proportion of the population that has the condition a given point in time, whereas *incidence* is the rate of occurrence of new cases. Incidence indicates the risk of developing or contracting the condition, whereas prevalence indicates how widespread the condition is. *Point prevalence* is the proportion of the population that has the condition at a single point in time. *Lifetime prevalence* is the proportion of the population that will ever have a condition at any point in their lifetime.

The *positivity rate* is the proportion of tests that are positive. The *case fatality rate* is the proportion of people with a condition who die as a result of that condition.

### The Three S's: Signs, Symptoms, and Syndromes

The Three S's of assessment in clinical psychology are signs, symptoms, and syndromes. *Signs* are observable features (or manifestations) of a disorder [@Lilienfeld2015]. Therefore, signs can be perceived by a clinician. By contrast, *symptoms* are unobservable manifestations of a disorder that can only be perceived by the client [@Lilienfeld2015]. The term "sign" has a connotation of being somewhat more objective than symptom because a symptom is based on the client's perceptions, but at least in clinical psychology (and also in many medical fields), both signs and symptoms have considerable elements of subjectivity. A *syndrome* is a collection of signs and symptoms that co-occur and may reflect a particular disorder.

## Errors of Pseudo-Prediction

There are many errors of pseudo-prediction that are relevant to clinical assessment. One error of pseudo-prediction is the confusion of inverse probabilities, as described in Section \@ref(inverseFallacy). Another error of pseudo-prediction involves, when predicting a low base-rate phenomenon, only capitalizing on chance occurrences.

Another form of pseudo-prediction is constructing predictions that seem compelling but that have no basis, for instance use the date and place of birth to predict one's personality. Several techniques are used by people to make their predictions seem more compelling: make it true, make it positive, make it ambiguous, and make it mysterious or intimidating. Making it "true" means surrounding predictions with true statements, and using Barnum statements. Barnum statements are statements that are true for most people, such as: "You have a tendency to be critical of yourself." Including, in your prediction, outcomes that are a common occurence for 80% of respondents (blanket statements) may make it more likely that people believe the prediction. Most of the statments are correct, so people tend to think the whole thing is correct. Making it "positive" means making the statement positive about the person. People tend to believe positive things about the self. However, if the statement is about a third person, people tend to believe it more if the statement is partially negative. Making it "ambiguous" means using vague language such as "it has not been unusual," "sometimes," "at times," "you tend to be," etc. Making it mysterious or intimidating could involve making the prediction from some organization or process with authority. An example of making statement mysterious is the PaTE report ("Psychodynamic and Therapeutic Evaluation").

Unsupported fad treatments.

Violating the extension rule (the conjucntion fallacy)

Imposing structure (non-randomness) on a pattern where there are none.

Expecting alternation, known as the "belief in the law of small numbers".

Spurious correlations

Multi-collinearity

Hot hand fallacy

Capitalizing on regression effects

## Conclusion