# Ethical Issues in Assessment {#ethics}

Ethics are relevant to all of our domains as psychologists, including (but not limited to) research, teaching, assessment, intervention, and supervision.

## Open Science

The open science movement is [define] [describe aims, goals and why]

To advance reproducibility and replicability in science, researchers are encouraged to provide greater transparency and sharing of their research. For instance, one way to provide greater transparency and to limit the researcher's degrees of freedom is to (pre-)register a study. There is a continuum of study registration that includes pre-registration, co-registration, and post-registration, depending on when the registration occurs relative to data collection and analysis [@Benning2019]. Study pre-registration involves publicly posting a study's design, methods, materials, hypothesis, and data analysis plan prior to data collection. Co-registration occurs after data collection starts but before data analysis begins. Post-registration occurs after data analysis has begun.

Some journals see the value of pre-registered studies and publish registered reports. A registered report is a study that is evaluated based on the pre-registered methods, hypotheses, and data analysis plan, and if the pre-registered study is accepted, the eventual paper will be accepted (as long as the researchers followed the pre-registered plan) regardless of whether the findings supported the hypotheses.

There are many tools that aim to advance the open science movement. A key one is the Open Science Framework (OSF; https://osf.io). There are numerous ways that researchers can make use of the Open Science Framework (OSF) to advance the aims of open science. Researchers can (pre-)register their study on the OSF by posting their hypotheses, study methods, and data analysis plan. In addition, researchers can use the OSF to post manuals, protocols, lab notebooks, data, data processing syntax, statistical analysis code, detailed results, computational notebooks, and paper preprints [@Tackett2019a].

## Conclusion