# Objective Personality Testing {#objective-personality}

[**Wright et al, 2019 citation in psych assessment**; **Bensch et al, 2019 citation** ;**Tackett et al, 2019 citation on MTMM**; **Simms et al. 2019 citation**; **Clark & Watson, 2019 citation**; **Sellbom & Tellegen, 2019**; **Wright & Zimmerman, 2019 citation**; **Burchett et al, 2019 citation**; **Chandler et al, 2020 citation**]

[**Costa et al, 2019 citation**]

[**Markon, 2019 article on bifactor models**]

## Overview of Personality Tests

There are two main types of personality tests: objective personality tests and projective personality tests. Of course, no measure is truly "objective" but some measures are more or less so. In a so-called *objective personality test*, a stimulus is presented to a respondent, who makes a closed-ended (constrained) response, such as True/False or Likert ratings. Examples of objective personality tests include the Minnesota Multiphasic Personality Inventory (MMPI) and the Beck Depression Inventory (BDI). In a *projective personality test*, an ambiguous stimulus is presented to a respondent, who is asked to make an open-ended response. Examples of projective personality tests include the Rorschach Inkblot Test and the Thematic Apperception Test (TAT). Projective tests have largely fallen by the wayside now, but it is still helpful to think about their potential advantages. Projective tests are described in further detail in Chapter \@ref(projective).

### Projective Personality Tests

In a projective personality test, the client's response is not limited. Projective personality tests were designed from a psychodynamic perspective, and they are supposed to have limitless variability and therefore a freer access to the client's internal world. However, one of the Rorschach Inkblot card looks like a moth or a bat, and around 80% of respondents give that response, so projective tests are not completely limitless. Projective personality tests are designed to have ambiguous content. This is, in part, to make them hard to figure out what is being assessed. However, even so-called objective personality tests can have items that are ambiguous and that function similar to a projective test. For instance, one of the items on the original MMPI asks respondents whether they like mechanics magazines. But, many people have never looked at a mechanics magazine. So, it becomes like a Rorschach question because the client starts to think about other factors.

Scoring of projective tests does not rely on the client's insight, so projective tests might get past social desirability of clients' responses and potential defensiveness. Therefore, projective tests are potentially difficult to fake. Faking good means to present oneself as better than one actually is, whereas faking bad means to present oneself as worse than one actually is. For instance, a client may want to fake good on a test if it allows them to keep custody of their child. By contrast, a client may want to fake bad to receive disability insurance.

As of 1995, the TAT and Rorschach were the #5 and #6 most widely used assessments, respectively, by clinical psychologists [@Watkins1995]. However, they and other projective techniques have lost considerable ground since then.

### Objective Personality Tests

In contrast to projective personality tests, objective personality tests, the client's responses are substantially constrained to the possible answers. Moreover, objective personality tests tend to be cheap and fast to administer, and can be scored by computers now. In addition, objective tests have more reliable scoring than projective tests. It is very long to score the Rorschach Inkblot Test and it it still has very low reliability. With an objective test, by contrast, scoring reliability approaches perfection. The earliest examples of objective personality tests were teh MMPI and the Strong Vocational Interest Blank. The MMPI assesses personality, whereas the Strong Vocational Interest Blank assessed preferences for different jobs or professions.

## Example of an Objective Personality Test: MMPI

Consider an example of a True/False item from the MMPI: "I hardly ever notice my heart pounding and I am seldom short of breath.". The item is intended to assess somatic symptom disorder. But, there are other factors that could influence a person's response to the question besides whether the person has somatic symptom disorder. The item is not clearly "objective" because constructs in the questions are not clearly defined. What does a "pounding heart" mean? How much is "hardly ever"? People may define "seldom" differently.

## Problems with Objective True/False Measures

## Approaches to Developing Personality Measures

### External Approach

#### Pros

#### Cons

### Deductive Approach

#### Pros

#### Cons

### Inductive Approach

#### Pros

#### Cons

### Hybrid Approach

## Measure Development and Item Selection

## The Flawed Nature of Self-Assessments

### Bias

### Ambiguity of Items

### Lack of Insight

### Satisficing (vs. Optimizing)

#### Optimizing

#### Satisficing

## Conclusion
	