# Projective Personality Testing {#projective}

## Overview of Projective Personality Testing

Surveys consistently show projective measures to be among the most commonly used assessment devices in clinical psychology, school psychology, and neuropsychology [see @Youngstrom2016]. There has been some decline in their usage, in part due to managed care and in part due to criticisms, but they are still widely used.

@Frank1939 presents a problem to solve—how best to assess personality—and their proposed solution. He sought to develop a predictive model of people's personality and behavior based on how people process information. The approach of predictive modeling has worked in other areas of psychology. According to their conceptual framework, people exists in multiple spheres:

1. in the common public world of nature (i.e., as humans)
2. as members of their social and cultural groups
3. as individuals in their private worlds of highly idiosyncratic meanings, significances, and feelings (i.e., personality)

When psychologists try to assess people's private worlds (personalities), they are not seeking to assess the cultural and social norms—instead they seek to assess the peculiarities of the individual. Psychodynamic theorists viewed standardized tests as a measure of how much a person conforms to the expectations of a cultural group, not as a measure of the person as an individual. Psychodynamic theorists viewed personality as a dynamic process of how a person organizes their experience according to the unique individual's private world. They viewed projective measures as an "X-ray of the soul" that reveals its components and organization, including the state, condition, and maturation of the organism.

Projective measures are an indirect method used to assess the internal organization and composition of an individual organism. According to the conceptual framework, projective measures allowed examiners to get a glimpse into this dynamic process and their private world by observing the examinee's response to various "fields." *Fields* are ambiguous stimuli consisting of objects, materials, and experiences with relatively little structure and cultural patterning. Psychodynamic theorists hypothesized that an individual's personality projects onto the field their way of seeing life, their meanings, significances, patterns, and feelings.

*Projection*, according to @Freud1911, is a defense mechanism by which people unconsciously attribute their negative personality traits and impulses to others. According to a psychodynamic framework, psychopathology is hypothesized to be caused by unconscious motives, conflicts, memories. In this framework, defense mechanisms keep us unaware of the painful contents of the unconscious. However, attributing negative characteristics to others does not appear to be effective in reducing anxiety or keeping one unaware of one's own negative characteristics.

Projective measures were thought to be a way to access a person's unconscious. When presented with a field (an ambiguous stimulus), the person has to organize the field, interpret the material, and react affectively to it. Therefore, according to the framework, projective measures elicit a projection of the individual personality's private world, that is how they organize their life space. Psychoanalysts seek to assess "what one cannot or will not say" because the person does not know themself well enough, and is unaware of what they are revealing about themself through their projections. According to this perspective, the person rarely has an understanding of themself or awareness of what their activities signify.

### Categorization of Responses

The psychoanalysis separates projections (i.e., responses to the ambiguous stimuli) into categories, such as:

- Constitution: forming a holistic entity or "Gestalt"
- Interpretive: describing what a stimulus-situation means to them
- Cathartic: discharging affect or feeling upon the stimulus-situation for emotional release
- Constructive: building with the materials in a way that reflects something meaningful about their life

### Projective Hypothesis

Psychodynamic theorists are less concerned with psychometrics ([reliability](#reliability) and [validity](#validity)) from statistical correlations across many people. Instead, they seek to assess one person in many ways to see how they structure their life space. They would argue that the projective measures are valid if the examinee provides similar response configurations across stimuli and situations.

Projective measures are based on the projective hypothesis. According to the *projective hypothesis*, whatever a person does when exposed to an ambiguous stimulus will reveal important aspects of the person's personality. An ancillary hypothesis to the projective hypothesis is that indirect responses are more [valid](#validity) than direct responses. Indirect responses are responses to ambiguous stimuli whereas direct responses are responses to interviews or questionnaires.

### Projective Measures

*Projective measures* are measures in which an ambiguous stimulus is presented to the respondent, who is asked to make an open-ended response. There is theoretical strength behind them in they they have good goals, but they are based on poor implementation. The goal of projective measures is to discover things that do not depend on self-knowledge and the person's ability or willingness to share it. Projective measures aim to bypass defense mechanisms so that they assess characteristics the person has and which the person is not consciously aware of. For example, projective measures aim to assess characteristics the person does not recognize or wants to hide.

Examples of projective measures include the [Rorschach Inkblot Test](#rorschach), the [Thematic Apperception Test](#tat) (TAT), Draw-A-Person Test, and drawing a family (Kinetic Family Drawing).

Most projective techniques do **not** have:

- standardized stimuli and testing instructions
- systematic algorithms for scoring responses to stimuli, or
- well-calibrated norms for comparing responses with those of other people

There are various types of projective measures, including measures that use:

- association techniques, often with an ambiguous form—e.g., inkblot, clouds, or word association tests
- construction techniques, often with artistic media—e.g., human figure drawing or story creation methods like the TAT. Thematic perception involves writing or telling stories about a series of pictures.
- completion techniques—e.g., sentence completion tests
- arrangement or selection techniques
- expression techniques, often with movement or play—e.g., projective doll play, puppetry, hand-writing analysis. Play is often used by psychoanalysts as a projective measure with children because it is thought that children have fewer defenses to hide behind (compared to adults) and are less aware of how much they are revealing through their play. For instance, psychoanalysts believe that children who have been abused will reveal that in their play configurations with dolls.

The [Rorschach Inkblot Test](#rorschach) is a classic example of a projective measure. It was designed by Swiss psychiatrist Hermann Rorschach in 1921. It was initially designed as an instrument for studying perception, but it became to be conceived of as a test of personality pathology. It was conceived by psychoanalysts as an "X-ray of the soul." The [Rorschach Inkblot Test](#rorschach) has low [face validity](#faceValidity), and is therefore potentially difficult to fake. For instance, a person may fake good (present as if they are better than they are) in the context of a custody evaluation or job interview, whereas a person may fake bad (present as if they are worse than they are) in the context of an evaluation for disability claims or of the person's sanity to stand trial.

In 1968, a projectively oriented, classic textbook was published, titled, "The Interpretation of Psychological tests." The textbook provides case examples of a patient. Examiners were trying to decide if the patient was psychotic, and interpret her [crystallized intelligence](#fluidCrystallizedIntelligence) from the Wechsler Adult Instelligence Scale based on [Rorschach](#rorschach) scores ("insufficiency of ego strength"). The examiners attributed her lack of consistency across items not to the inconsistency in the test (and its stimuli), but to her own inconsistencies.

### Why Not Use Projective Measures?

There are many reasons not to use projective measures. First, they can be very time consuming: both for the client and the psychologist, in terms of administration, scoring, and interpretation. Second, they provide very little information. You could just ask clients questions on a questionnaire or in an interview. Consider the example of assessing a client for depression. Instead of relying on the client to report relatively color-less items in the [Rorschach](#rorschach), why not ask them how their mood is and observe the energy and affect? Thus, projective measures have an [incremental validity](#incrementalValidity) problem. The scientific status of projective measures are described in further detail later in the chapter in Section \@ref(projectiveScientificStatus).

## Examples of Projective Measures

In this chapter, two projective measures are described in detail. The first is the [Rorschach Inkblot Test](#rorschach) and the second is the [Thematic Apperception Test](#tat) (TAT).

### Rorschach Inkblot Test {#rorschach}

The Rorschach Inkblot Test was designed by Hermann Rorschach in 1921 and has ten inkblots, five of which are black and white, and five of which contain color. The measure is composed of three phases, depending on whether one is using the Comprehensive System (CS) [@Exner1974; @Exner2005] or the Rorschach Performance Assessment System (R-PAS) [@Meyer2011]. The phases include: 1) the Free Association (CS) or Response (R-PAS) Phase, 2) the Inquiry (CS) or Clarification (R-PAS) Phase, and 3) the Follow-Up Phase.

In the "Free Association" or "Response" phase, the examinee is handed one inkblot card at a time and is asked what they see. The stimuli were designed with an aim to provide the least amount of intrinsic information; the test developers did not want to impose intrinsic information from concrete stimuli. The inkblots start completely black and white, then they move to grayscale, which was considered to be "easier emotionally" for clients, and then color inkblots are shown, which was considered more challenging emotionally. The clinician intends not to guide the examinee to particular responses, but they also want to hear more than one response. The idea is that eventually, with additional responses, the examinee will get to be less censored.

After finishing the response phase, the clinician moves to the "Inquiry" or "Clarification" phase, in which the examiner reminds the examinee of the examinee's responses and ask where on the card the examinee saw their responses and what about the inkblot made it look like that. The clinician inquires what part of the card includes the image the examinee had described. The examinee then identifies the location in the card, i.e., whether it is the whole card or particular parts of the card, or excluded parts (negative space) of the card. It involves asking the examinee what exactly they saw, and what (determinants) made them see that. It also involves examining whether they use integration to complete the whole picture. Or if they are more defensive, it is hypothesized that the examinee will pick out a little part of the picture when describing what they see. Then, they are asked to flip the card around. The inquiry phase can last a long time, sometimes one hour 1 hour or more.

In the open-ended "Follow-Up" phase, the examiner tries to learn what the examinee was thinking and the process that may have led to the response obtained [@Choca2018]. The examiner may use a technique called "testing the limits." This may involve additional questions or observations. For instance, questions might ask why a respondent may not see what many others see. Did the person see two insects or two people? Were they males or females? Observations might include noting that the examinee provided many responses.

#### Variables

There are a number of variables that are often scored in a Rorschach administration. Here are some of the ones that can be scored:

- Latency to respond
    - Let the examinee stew for a while because the first response is the least interesting because it is the most obvious
- How are they holding the card? How do they turn the card? How many times do they turn the card?
- What content do they see and describe in the inkblot?
    - Do they see sexual content? Violent content?
- Location: did the examinee see the whole blot as a picture or just one particular area of the blot, or excluded parts (negative space) of the card?
- Determinants: the parts of it
    - Color: lack of color is hypothesized to reflect depression
    - Shape
    - Movement: hypothesized to reflect intelligence
    - Feel, texture
    - From a distance, landscape

#### Scoring

The clinician then can spend several hours scoring, and there are many different potential indices. Whether the content described by the examinee is considered good or bad is based on textbook judgments. This could represent an example of an illusory correlation. An *illusory correlation* is the tendency to perceive associations between signs and psychopathology even when they do not exist.

John Exner [-@Exner1974] developed standardized rules for administration and scoring, which improved the [reliability](#reliability) of scores. The Exner system, also known as the "Comprehensive System" (CS) [@Exner1974; @Exner2005] is the most widely used scoring system for the Rorschach. But, there are still major problems with the system. A more recent scoring system has been developed, known as the Rorschach Performance Assessment System (R-PAS) [@Meyer2011]. R-PAS has limited research on its use by those outside of its developers, but it likely has similar problems with [validity](#validity) and [utility](#utility).

### Thematic Apperception Test (TAT) {#tat}

The Thematic Apperception Test (TAT) is described by @Lindzey1952. The TAT was developed by Christiana Morgan and Henry Murray in 1935 [@Morgan1935]. The TAT is more about storytelling, and having the examinee tell a story. So, unlike the [Rorschach](#rorschach), storytelling is allowed in the TAT. It was developed by scientists, and there has been a lot of research on and using the TAT.

The TAT aims to get a better understanding of underlying motivations (e.g., achievement motivation), and it is thought by psychoanalysts to assess implicit motives, unlike self-attributed motives assessed by self-report instruments. Most stimuli in the TAT involve humans, but the situations are ambiguous.

Examinees' responses on the TAT are strongly predictive of various motivations, but they are no more predictive than just asking people their motivations. Motivations that are intended to be assessed by the TAT include: achievement motivation, need for power, need for affiliation, and object relations. Object relations are people's mental representations of other people.

The administrator picks cards to administer that "pull" at issues of interest related to the respondent's presenting difficulties. As a result, the TAT is non-standardized. The examiner asks the examinee what is going on in the picture, what the characters are thinking and feeling, what led up to it, and how it ended.

The examiner might examine the respondent's response latency, and writes down all words of the response. They would examine who the examinee is relating to and identifying with. The examiner seeks to identify patterns and commonalities across stories in response to different TAT cards.

Towards the end of the story, there is very little information from the card, so the respondent has to fill in the story. Thus, psychoanalysts believe that responses at the end of the story are the most "pure," and come from the inside (as opposed to external factors).

The examiner pays attention for themes that are consistent across cards. However, fantasy behavior is not the same as actual behavior. For instance, telling violent stories is not the same as being violent. The horror author, Stephen King is an apt example of how describing violence does not mean that the person is violent.

## Most Widely Used Assessments for Children

Projective assessments are widely used. As of 2002, the top 30 most widely used assessments for children [@Cashel2002] include:

- Wechsler Intelligence Scale for Children
- [Child Behavior Checklist](#behaviorRatingScales)
- And then many projective techniques, including:
    - Sentence completion
    - Draw-A-Person test (with psychodynamic oriented scoring)
    - House–Tree–Person Technique
    - Kinetic Family Drawing
    - [Rorschach Inkblot Test](#rorschach)
    - [Thematic Apperception Test](#tat) (TAT)
    - Children's Apperception Test (Children's TAT)

In sum, seven of the most widely used assessments for children are projective tests.

## Evaluating the Scientific Status of Projective Measures {#projectiveScientificStatus}

Given that projective assessments are so widely used, it would be expected that they have a strong scientific status. @Lilienfeld2000 evaluated the scientific status of projective techniques. To evaluate the scientific status of the [Rorschach Inkblot Test](#rorschach) (or any other projective measure), I would assess across several domains of evidence, as described below. Evaluation of the [Rorschach Inkblot Test](#rorschach) is provided by Wood and colleagues [-@Wood1996; -@Wood1996a; -@Wood2001b].

### Utility of Norms

One consideration to evaluate is the utility of the [norms](#norm). This includes assessing if the normative information on which scoring of the test is based sets the cut-off accurately for those with and without maladaptive behavior, across cultural and minority groups. Of note, the [Rorschach](#rorschach) does not correctly distinguish between those with and without maladaptive behavior, and does not lead to unbiased estimates for ethnic minorities. In addition, we cannot evaluate the [norms](#norm) because they are not published.

In terms of the Exner [norms](#norm), they showed somewhat higher [reliability](#reliability) than the original [Rorschach](#rorschach) [norms](#norm), but they did not show strong evidence for [validity](#validity). The Exner [norms](#norm) are not well-calibrated. The Exner [norms](#norm) result in over-diagnosis and over-pathologizing of normality. And they are not representative and generalizable: there are ethnic and cultural [biases](#bias).

### Reliability of Scores

Another important consideration of projective measures is the [reliability](#reliability) of scores. This would include evaluating both [inter-rater reliability](interrater-reliability) and [test-retest reliability](testRetest-reliability). For the [Rorschach](#rorschach), the [inter-rater reliability](interrater-reliability) depends on the subscale of diagnosis, and has to be much lower than that of [objective techniques](#objective-personality), especially in field settings. Field [reliability](#reliability) refers to [reliability](#reliability) in actual practice rather than ideal [reliability](#reliability) in optimal conditions of a controlled lab study. The [reliability](#reliability) and standardization of administration of the [Rorschach](#rorschach) is also questionable. The [test-retest reliability](testRetest-reliability) is also low—but high enough to be passable for research settings—but it should be used with caution in clinical diagnostic settings.

### Influence of Measurement Error on Scores

Another important consideration is the influence of [measurement error](#measurementError) on scores: one aspect of the [Rorschach](#rorschach) in particular that can lead to [measurement error](#measurementError) is the effect of response frequency on test [validity](#validity). If people provide more answers, which is correlated with intelligence, these people are more likely to express a deviant answer indicative of maladjustment.

### Validity

A crucial consideration of the scientific status is their [validity](#validity). [Validity](#validity) is not a yes/no thing. It is important to ask what the [validity](#validity) is for what purpose? [Rorschach](#rorschach) responses can be moderately [valid](#validity) indicators of creativity. Projective drawings have moderate [validity](#validity) for drawing ability. But, are projective tests [valid](#validity) for their typical purposes in clinical psychology? For instance, do they have diagnostic accuracy? Their accuracy for their typical purposes in clinical psychology is discussed below.

#### Criterion-Related Validity

[Criterion-related validity](#criterionValidity) would consider whether the diagnosis given on the basis of the [Rorschach](#rorschach) aligns with an external criterion of an actual diagnosis. For the [Rorschach](#rorschach), the answer is: not really. Scores have some relation to psychosis and thought disorders, but they are not strongly related to other aspects of psychopathology. Research designs comparing diagnostic versus control groups often over-estimate [predictive validity](#predictiveValidity) of the [Rorschach](#rorschach) compared to what it would be in practice because clinicians are typically interested in low [base rate](#baseRate) phenomena for which predictive accuracy will be lower.

#### Convergent Validity

[Convergent validity](#convergentValidity) would consider whether [Rorschach](#rorschach) findings correspond to the findings of more [reliable](#reliability) [objective](#objective-personality) tests such as the [Minnesota Multiphasic Personality Inventory](#mmpi)? The answer is also no.

#### Incremental Validity

In terms of [incremental validity](#incrementalValidity), a frequent argument by proponents of projective tests is that, "I don't use the [Rorschach](#rorschach)/[TAT](#tat) in isolation but in combination with other measures." But does the inclusion of the [Rorschach](#rorschach) lead to improvements in the [validity](#validity) of diagnoses of clinicians? No. In many cases it has [*decremental* validity](#incrementalValidity)—it decreases predictive or diagnostic accuracy.

#### Treatment Utility

[Treatment utility](#treatmentUtility) considers whether it is worth the vast amount of time spent administering, scoring, and interpreting the measure (2–3 hours)? The answer is also no. You can assess psychopathology more accurately with more [reliable](#reliability) and less time-consuming measures, including interviews, questionnaires, and demographic data. Projective measures present actual costs in addition to opportunity costs. Actual costs of projective measures include that they are expensive and time-consuming for training, and are time-consuming to administer, score, and interpret. Opportunity costs of projective measures include that it takes time away from other, more useful procedures.

### Summary

Hence, I would not say the scientific status of the [Rorschach](#rorschach) is very positive. The evidence does not provide the evidence necessary to call projective measures "tests." No known projective measures have enough power to justify their lengthy use. Considering the important role that assessments can play in clinical decision making that influences people's lives, it seems unethical to use projective techniques, as they are currently designed and used.

## Conclusion

## Suggested Readings

@Lilienfeld2000
