# Projective Personality Testing {#projective}

## Overview of Projective Personality Testing {#overview-projective-personality}

Surveys consistently show projective measures to be among the most commonly used assessment devices in clinical psychology, school psychology, and neuropsychology [see @Youngstrom2016].\index{personality assessment!projective}
There has been some decline in their usage, in part due to managed care and in part due to criticisms, but they are still widely used.\index{personality assessment!projective}\index{managed care}

@Frank1939 presents a problem to solve—how best to assess personality—and their proposed solution.\index{personality assessment!projective}
He sought to develop a predictive model of people's personality and behavior based on how people process information.\index{personality assessment!projective}
The approach of predictive modeling has worked in other areas of psychology.
According to their conceptual framework, people exists in multiple spheres:\index{personality assessment!projective}

1. in the common public world of nature (i.e., as humans)\index{personality assessment!projective}
1. as members of their social and cultural groups\index{personality assessment!projective}
1. as individuals in their private worlds of highly idiosyncratic meanings, significances, and feelings (i.e., personality)\index{personality assessment!projective}

When psychologists try to assess people's private worlds (personalities), they are not seeking to assess the cultural and social norms—instead they seek to assess the peculiarities of the individual.\index{personality assessment!projective}
Psychodynamic theorists viewed standardized tests as a measure of how much a person conforms to the expectations of a cultural group, not as a measure of the person as an individual.\index{personality assessment!projective}\index{psychoanalysis}
Psychodynamic theorists viewed personality as a dynamic process of how a person organizes their experience according to the unique individual's private world.\index{personality assessment!projective}\index{psychoanalysis}
They viewed projective measures as an "X-ray of the soul" that reveals its components and organization, including the state, condition, and maturation of the organism.\index{personality assessment!projective}\index{psychoanalysis}

Projective measures are an indirect method used to assess the internal organization and composition of an individual organism.\index{personality assessment!projective}
According to the conceptual framework, projective measures allowed examiners to get a glimpse into this dynamic process and their private world by observing the examinee's response to various "fields."\index{personality assessment!projective}
*Fields* are ambiguous stimuli consisting of objects, materials, and experiences with relatively little structure and cultural patterning.\index{personality assessment!projective!fields}\index{psychoanalysis!field}
Psychodynamic theorists hypothesized that an individual's personality projects onto the field their way of seeing life, their meanings, significances, patterns, and feelings.\index{personality assessment!projective}

*Projection*, according to @Freud1911, is a defense mechanism by which people unconsciously attribute their negative personality traits and impulses to others.\index{personality assessment!projective}\index{psychoanalysis!projection}
According to a psychodynamic framework, psychopathology is hypothesized to be caused by unconscious motives, conflicts, memories.\index{personality assessment!projective}\index{psychoanalysis}
In this framework, defense mechanisms keep us unaware of the painful contents of the unconscious.\index{personality assessment!projective}\index{psychoanalysis}\index{psychoanalysis!defense mechanism}
However, attributing negative characteristics to others does not appear to be effective in reducing anxiety or keeping one unaware of one's own negative characteristics.\index{personality assessment!projective}\index{psychoanalysis}\index{psychoanalysis!defense mechanism}

Projective measures were thought to be a way to access a person's unconscious.\index{personality assessment!projective}\index{psychoanalysis}
When presented with a field (an ambiguous stimulus), the person has to organize the field, interpret the material, and react affectively to it.\index{personality assessment!projective!fields}\index{psychoanalysis!field}
Therefore, according to the framework, projective measures elicit a projection of the individual personality's private world, that is how they organize their life space.\index{personality assessment!projective!fields}\index{psychoanalysis!projection}\index{psychoanalysis}
Psychoanalysts seek to assess "what one cannot or will not say" because the person does not know themself well enough, and is unaware of what they are revealing about themself through their projections.\index{personality assessment!projective}\index{personality assessment!projective!fields}\index{psychoanalysis}
According to this perspective, the person rarely has an understanding of themself or awareness of what their activities signify.\index{personality assessment!projective}\index{psychoanalysis}

### Categorization of Responses {#projectiveCategorization}

The psychoanalysis separates projections (i.e., responses to the ambiguous stimuli) into categories, such as:\index{personality assessment!projective}\index{psychoanalysis}

- Constitution: forming a holistic entity or "Gestalt"\index{personality assessment!projective}\index{psychoanalysis}
- Interpretive: describing what a stimulus-situation means to them\index{personality assessment!projective}\index{psychoanalysis}
- Cathartic: discharging affect or feeling upon the stimulus-situation for emotional release\index{personality assessment!projective}\index{psychoanalysis}
- Constructive: building with the materials in a way that reflects something meaningful about their life\index{personality assessment!projective}\index{psychoanalysis}

### Projective Hypothesis {#projectiveHypothesis}

Psychodynamic theorists are less concerned with psychometrics ([reliability](#reliability) and [validity](#validity)) from statistical correlations across many people.\index{personality assessment!projective}\index{reliability}\index{validity}\index{psychoanalysis!projection}\index{psychoanalysis}
Instead, they seek to assess one person in many ways to see how they structure their life space.\index{personality assessment!projective}\index{reliability}\index{validity}\index{psychoanalysis!projection}\index{psychoanalysis}
They would argue that the projective measures are [valid](#validity) if the examinee provides similar response configurations across stimuli and situations.\index{personality assessment!projective}\index{validity}\index{psychoanalysis!projection}\index{psychoanalysis}

Projective measures are based on the projective hypothesis.\index{personality assessment!projective}\index{psychoanalysis!projection}
According to the *projective hypothesis*, whatever a person does when exposed to an ambiguous stimulus will reveal important aspects of the person's personality.\index{personality assessment!projective}\index{psychoanalysis!projection}
An ancillary hypothesis to the projective hypothesis is that indirect responses are more [valid](#validity) than direct responses.\index{personality assessment!projective}\index{psychoanalysis!projection}\index{validity}
Indirect responses are responses to ambiguous stimuli whereas direct responses are responses to interviews or questionnaires.\index{personality assessment!projective}\index{psychoanalysis!projection}

### Projective Measures {#projectiveMeasures}

*Projective measures* are measures in which an ambiguous stimulus is presented to the respondent, who is asked to make an open-ended response.\index{personality assessment!projective}
There is theoretical strength behind them in they they have good goals, but they are based on poor implementation.\index{personality assessment!projective}
The goal of projective measures is to discover things that do not depend on self-knowledge and the person's ability or willingness to share it.\index{personality assessment!projective}
Projective measures aim to bypass defense mechanisms so that they assess characteristics the person has and which the person is not consciously aware of.\index{personality assessment!projective}\index{psychoanalysis!defense mechanism}
For example, projective measures aim to assess characteristics the person does not recognize or wants to hide.\index{personality assessment!projective}

Examples of projective measures include the [Rorschach Inkblot Test](#rorschach), the [Thematic Apperception Test](#tat) (TAT), Draw-A-Person Test, and drawing a family (Kinetic Family Drawing).\index{personality assessment!projective}\index{Rorschach Inkblot Test}\index{Thematic Apperception Test}

Most projective techniques do **not** have:\index{personality assessment!projective}

- standardized stimuli and testing instructions\index{personality assessment!projective}\index{standardization}
- systematic algorithms for scoring responses to stimuli, or\index{personality assessment!projective}\index{standardization}
- well-calibrated [norms](#norm) for comparing responses with those of other people\index{personality assessment!projective}\index{norm}

There are various types of projective measures, including measures that use:\index{personality assessment!projective}

- association techniques, often with an ambiguous form—e.g., inkblot, clouds, or word association tests\index{personality assessment!projective}
- construction techniques, often with artistic media—e.g., human figure drawing or story creation methods like the [TAT](#tat).\index{personality assessment!projective}
Thematic perception involves writing or telling stories about a series of pictures.\index{personality assessment!projective}
- completion techniques—e.g., sentence completion tests\index{personality assessment!projective}
- arrangement or selection techniques\index{personality assessment!projective}
- expression techniques, often with movement or play—e.g., projective doll play, puppetry, hand-writing analysis.\index{personality assessment!projective}
Play is often used by psychoanalysts as a projective measure with children because it is thought that children have fewer defenses to hide behind (compared to adults) and are less aware of how much they are revealing through their play.\index{personality assessment!projective}
For instance, psychoanalysts believe that children who have been abused will reveal that in their play configurations with dolls.\index{personality assessment!projective}

The [Rorschach Inkblot Test](#rorschach) is a classic example of a projective measure.\index{personality assessment!projective}\index{Rorschach Inkblot Test}
It was designed by Swiss psychiatrist Hermann Rorschach in 1921.\index{personality assessment!projective}\index{Rorschach Inkblot Test}
It was initially designed as an instrument for studying perception, but it became to be conceived of as a test of personality pathology.\index{personality assessment!projective}\index{Rorschach Inkblot Test}
It was conceived by psychoanalysts as an "X-ray of the soul."\index{personality assessment!projective}\index{Rorschach Inkblot Test}
The [Rorschach Inkblot Test](#rorschach) has low [face validity](#faceValidity), and is therefore potentially difficult to fake.\index{personality assessment!projective}\index{Rorschach Inkblot Test}\index{validity!face}
For instance, a person may fake good (present as if they are better than they are) in the context of a custody evaluation or job interview, whereas a person may fake bad (present as if they are worse than they are) in the context of an evaluation for disability claims or of the person's sanity to stand trial.\index{personality assessment!projective}\index{Rorschach Inkblot Test}\index{faking!good}\index{faking!bad}

In 1968, a projectively oriented, classic textbook was published, titled, "The Interpretation of Psychological tests."\index{personality assessment!projective}
The textbook provides case examples of a patient.\index{personality assessment!projective}
Examiners were trying to decide if the patient was psychotic, and interpret her [crystallized intelligence](#fluidCrystallizedIntelligence) from the Wechsler Adult Instelligence Scale based on [Rorschach](#rorschach) scores ("insufficiency of ego strength").\index{personality assessment!projective}\index{Rorschach Inkblot Test}\index{intelligence!Wechsler scales}\index{intelligence!crystallized}
The examiners attributed her lack of consistency across items not to the inconsistency in the test (and its stimuli), but to her own inconsistencies.\index{personality assessment!projective}\index{reliability!internal consistency}\index{personality assessment!projective!reliability of}

### Why Not Use Projective Measures? {#whyNotUseProjectiveMeasures}

Projective measures can be considered examples of performance-based assessments.\index{performance-based assessment}
It can be helpful to include performance-based assessments as part of a broader assessment battery to avoid exclusive reliance on self-report.\index{performance-based assessment}\index{self-report}
From this perspective, one might think that it could be beneficial to use projective measures.\index{personality assessment!projective}
However, there are many reasons not to use projective measures.\index{personality assessment!projective}
First, projective measures can be very time consuming: both for the client and the psychologist, in terms of administration, scoring, and interpretation.\index{personality assessment!projective}
Second, unlike other [observational](#behavioral) and performance-based measures, projective measures provide very little information.\index{personality assessment!projective}
You could just ask clients questions on a questionnaire or in an interview.\index{personality assessment!projective}\index{questionnaire}\index{interview}
Consider the example of assessing a client for depression.\index{personality assessment!projective}
Instead of relying on the client to report relatively color-less items in the [Rorschach](#rorschach), why not ask them (and others) how their mood is and observe the energy and affect?\index{personality assessment!projective}\index{self-report}\index{observation}\index{Rorschach Inkblot Test}
Thus, projective measures have an [incremental validity](#incrementalValidity) problem.\index{personality assessment!projective}\index{validity!incremental}
The scientific status of projective measures is described in further detail later in the chapter in Section \@ref(projectiveScientificStatus).\index{personality assessment!projective}

## Examples of Projective Measures {#projectiveMeasureExamples}

In this chapter, two projective measures are described in detail.\index{personality assessment!projective}
The first is the [Rorschach Inkblot Test](#rorschach) and the second is the [Thematic Apperception Test](#tat) (TAT).\index{personality assessment!projective}\index{Rorschach Inkblot Test}\index{Thematic Apperception Test}

### Rorschach Inkblot Test {#rorschach}

The Rorschach Inkblot Test was designed by Hermann Rorschach in 1921 and has ten inkblots, five of which are black and white, and five of which contain color.\index{Rorschach Inkblot Test}
The measure is composed of three phases, depending on whether one is using the Comprehensive System (CS) [@Exner1974; @Exner2005] or the Rorschach Performance Assessment System (R-PAS) [@Meyer2011].\index{Rorschach Inkblot Test}
The phases include: (1) the Free Association (CS) or Response (R-PAS) Phase, (2) the Inquiry (CS) or Clarification (R-PAS) Phase, and (3) the Follow-Up Phase.\index{Rorschach Inkblot Test}

In the "Free Association" or "Response" phase, the examinee is handed one inkblot card at a time and is asked what they see.\index{Rorschach Inkblot Test}
The stimuli were designed with an aim to provide the least amount of intrinsic information; the test developers did not want to impose intrinsic information from concrete stimuli.\index{Rorschach Inkblot Test}
The inkblots start completely black and white, then they move to grayscale, which was considered to be "easier emotionally" for clients, and then color inkblots are shown, which was considered more challenging emotionally.\index{Rorschach Inkblot Test}
The clinician intends not to guide the examinee to particular responses, but they also want to hear more than one response.\index{Rorschach Inkblot Test}
The idea is that eventually, with additional responses, the examinee will get to be less censored.\index{Rorschach Inkblot Test}

After finishing the response phase, the clinician moves to the "Inquiry" or "Clarification" phase, in which the examiner reminds the examinee of the examinee's responses and ask where on the card the examinee saw their responses and what about the inkblot made it look like that.\index{Rorschach Inkblot Test}
The clinician inquires what part of the card includes the image the examinee had described.\index{Rorschach Inkblot Test}
The examinee then identifies the location in the card, i.e., whether it is the whole card or particular parts of the card, or excluded parts (negative space) of the card.\index{Rorschach Inkblot Test}
It involves asking the examinee what exactly they saw, and what (determinants) made them see that.\index{Rorschach Inkblot Test}
It also involves examining whether they use integration to complete the whole picture.\index{Rorschach Inkblot Test}
Or if they are more defensive, it is hypothesized that the examinee will pick out a little part of the picture when describing what they see.\index{Rorschach Inkblot Test}
Then, they are asked to flip the card around.\index{Rorschach Inkblot Test}
The inquiry phase can last a long time, sometimes one hour 1 hour or more.\index{Rorschach Inkblot Test}

In the open-ended "Follow-Up" phase, the examiner tries to learn what the examinee was thinking and the process that may have led to the response obtained [@Choca2018].\index{Rorschach Inkblot Test}
The examiner may use a technique called "testing the limits."\index{Rorschach Inkblot Test}
This may involve additional questions or observations.\index{Rorschach Inkblot Test}
For instance, questions might ask why a respondent may not see what many others see.\index{Rorschach Inkblot Test}
Did the person see two insects or two people?\index{Rorschach Inkblot Test}
Were they males or females?\index{Rorschach Inkblot Test}
Observations might include noting that the examinee provided many responses.\index{Rorschach Inkblot Test}

#### Variables {#rorschachVariables}

There are a number of variables that are often scored in a Rorschach administration.\index{Rorschach Inkblot Test!variables}
Here are some of the ones that can be scored:\index{Rorschach Inkblot Test!variables}

- Latency to respond\index{Rorschach Inkblot Test!variables}
    - Let the examinee stew for a while because the first response is the least interesting because it is the most obvious\index{Rorschach Inkblot Test!variables}
- How are they holding the card?\index{Rorschach Inkblot Test!variables}
How do they turn the card?\index{Rorschach Inkblot Test!variables}
How many times do they turn the card?\index{Rorschach Inkblot Test!variables}
- What content do they see and describe in the inkblot?\index{Rorschach Inkblot Test!variables}
    - Do they see sexual content?\index{Rorschach Inkblot Test!variables}
Violent content?\index{Rorschach Inkblot Test!variables}
- Location: did the examinee see the whole blot as a picture or just one particular area of the blot, or excluded parts (negative space) of the card?\index{Rorschach Inkblot Test!variables}
- Determinants: the parts of it\index{Rorschach Inkblot Test!variables}
    - Color: lack of color is hypothesized to reflect depression\index{Rorschach Inkblot Test!variables}
    - Shape\index{Rorschach Inkblot Test!variables}
    - Movement: hypothesized to reflect intelligence\index{Rorschach Inkblot Test!variables}
    - Feel, texture\index{Rorschach Inkblot Test!variables}
    - From a distance, landscape\index{Rorschach Inkblot Test!variables}

#### Scoring {#rorschachScoring}

The clinician then can spend several hours scoring, and there are many different potential indices.\index{Rorschach Inkblot Test!scoring}
Whether the content described by the examinee is considered good or bad is based on textbook judgments.\index{Rorschach Inkblot Test!scoring}
This could represent an example of an illusory correlation.\index{Rorschach Inkblot Test!scoring}
An *illusory correlation* is the tendency to perceive associations between signs and psychopathology even when they do not exist.\index{Rorschach Inkblot Test!scoring}\index{illusory correlation}

John Exner [-@Exner1974] developed standardized rules for administration and scoring, which improved the [reliability](#reliability) of scores.\index{Rorschach Inkblot Test!scoring}\index{Rorschach Inkblot Test!reliability}
The Exner system, also known as the "Comprehensive System" (CS) [@Exner1974; @Exner2005] is the most widely used scoring system for the Rorschach.\index{Rorschach Inkblot Test!scoring}
But there are still major problems with the system.\index{Rorschach Inkblot Test!scoring}
A more recent scoring system has been developed, known as the Rorschach Performance Assessment System (R-PAS) [@Meyer2011].\index{Rorschach Inkblot Test!scoring}
R-PAS has limited research on its use by those outside of its developers, but it likely has similar problems with [validity](#validity) and [utility](#utility).\index{Rorschach Inkblot Test!scoring}\index{Rorschach Inkblot Test!validity}\index{validity!utility}

### Thematic Apperception Test (TAT) {#tat}

The Thematic Apperception Test (TAT) is described by @Lindzey1952.\index{Thematic Apperception Test}
The TAT was developed by Christiana Morgan and Henry Murray in 1935 [@Morgan1935].\index{Thematic Apperception Test}
The TAT is more about storytelling, and having the examinee tell a story.\index{Thematic Apperception Test}
So, unlike the [Rorschach](#rorschach), storytelling is allowed in the TAT.\index{Thematic Apperception Test}\index{Rorschach Inkblot Test}
It was developed by scientists, and there has been a lot of research on and using the TAT.\index{Thematic Apperception Test}

The TAT aims to get a better understanding of underlying motivations (e.g., achievement motivation), and it is thought by psychoanalysts to assess implicit motives, unlike self-attributed motives assessed by self-report instruments.\index{Thematic Apperception Test}
Most stimuli in the TAT involve humans, but the situations are ambiguous.\index{Thematic Apperception Test}

Examinees' responses on the TAT are strongly predictive of various motivations, but they are no more predictive than just asking people their motivations.\index{Thematic Apperception Test}
Motivations that are intended to be assessed by the TAT include: achievement motivation, need for power, need for affiliation, and object relations.\index{Thematic Apperception Test}
Object relations are people's mental representations of other people.\index{Thematic Apperception Test}

The administrator picks cards to administer that "pull" at issues of interest related to the respondent's presenting difficulties.\index{Thematic Apperception Test}
As a result, the TAT is non-standardized.\index{Thematic Apperception Test}\index{standardization}
The examiner asks the examinee what is going on in the picture, what the characters are thinking and feeling, what led up to it, and how it ended.\index{Thematic Apperception Test}

The examiner might examine the respondent's response latency, and writes down all words of the response.\index{Thematic Apperception Test}
They would examine who the examinee is relating to and identifying with.\index{Thematic Apperception Test}
The examiner seeks to identify patterns and commonalities across stories in response to different TAT cards.\index{Thematic Apperception Test}

Towards the end of the story, there is very little information from the card, so the respondent has to fill in the story.\index{Thematic Apperception Test}
Thus, psychoanalysts believe that responses at the end of the story are the most "pure," and come from the inside (as opposed to external factors).\index{Thematic Apperception Test}\index{psychoanalysis}

The examiner pays attention for themes that are consistent across cards.\index{Thematic Apperception Test}
However, fantasy behavior is not the same as actual behavior.\index{Thematic Apperception Test}
For instance, telling violent stories is not the same as being violent.\index{Thematic Apperception Test}
The horror author, Stephen King is an apt example of how describing violence does not mean that the person is violent.\index{Thematic Apperception Test}

## Most Widely Used Assessments for Children {#mostWidelyUsedAssessmentsChildren}

Projective assessments are widely used.\index{personality assessment!projective}
As of 2002, the top 30 most widely used assessments for children [@Cashel2002] include:

- Wechsler Intelligence Scale for Children\index{intelligence!Wechsler scales}
- [Child Behavior Checklist](#behaviorRatingScales)\index{behavior rating scale}\index{Child Behavior Checklist}
- And then many projective techniques, including:
    - Sentence completion\index{personality assessment!projective}
    - Draw-A-Person test (with psychodynamic oriented scoring)\index{personality assessment!projective}
    - House–Tree–Person Technique\index{personality assessment!projective}
    - Kinetic Family Drawing\index{personality assessment!projective}
    - [Rorschach Inkblot Test](#rorschach)\index{personality assessment!projective}\index{Rorschach Inkblot Test}
    - [Thematic Apperception Test](#tat) (TAT)\index{personality assessment!projective}\index{Thematic Apperception Test}
    - Children's Apperception Test (Children's TAT)\index{personality assessment!projective}\index{Thematic Apperception Test}

In sum, seven of the most widely used assessments for children are projective tests.\index{personality assessment!projective}

## Evaluating the Scientific Status of Projective Measures {#projectiveScientificStatus}

Given that projective assessments are so widely used, it would be expected that they have a strong scientific status.\index{personality assessment!projective}\index{personality assessment!projective!scientific status}
@Lilienfeld2000 evaluated the scientific status of projective techniques.\index{personality assessment!projective}\index{personality assessment!projective!scientific status}
To evaluate the scientific status of the [Rorschach Inkblot Test](#rorschach) (or any other projective measure), I would assess across several domains of evidence, as described below.\index{personality assessment!projective}\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test}
Evaluation of the [Rorschach Inkblot Test](#rorschach) is provided by Wood and colleagues [-@Wood1996; -@Wood1996a; -@Wood2001b].\index{personality assessment!projective}\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test}

### Utility of Norms {#projectiveNorms}

One consideration to evaluate is the utility of the [norms](#norm).\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test}\index{norm}
This includes assessing if the normative information on which scoring of the test is based sets the cut-off accurately for those with and without maladaptive behavior, across cultural and minority groups.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test}
Of note, the [Rorschach](#rorschach) does not correctly distinguish between those with and without maladaptive behavior, and does not lead to unbiased estimates for ethnic minorities.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test}
In addition, we cannot evaluate the [norms](#norm) because they are not published.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test}\index{norm}

In terms of the Exner [norms](#norm), they showed somewhat higher [reliability](#reliability) than the original [Rorschach](#rorschach) [norms](#norm), but they did not show strong evidence for [validity](#validity).\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test}\index{norm}\index{Rorschach Inkblot Test!validity}\index{Rorschach Inkblot Test!reliability}
The Exner [norms](#norm) are not well-calibrated.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test}\index{norm}
The Exner [norms](#norm) result in over-diagnosis and over-pathologizing of normality.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test}\index{norm}
And they are not representative and generalizable: there are ethnic and cultural [biases](#bias).\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test}\index{norm}\index{bias}

### Reliability of Scores {#projectiveReliability}

Another important consideration of projective measures is the [reliability](#reliability) of scores.\index{personality assessment!projective!scientific status}
This would include evaluating both [inter-rater reliability](#interrater-reliability) and [test–retest reliability](#testRetest-reliability).\index{personality assessment!projective!scientific status}\index{reliability!inter-rater}\index{reliability!test–retest}
For the [Rorschach](#rorschach), the [inter-rater reliability](#interrater-reliability) depends on the subscale of diagnosis, and has to be much lower than that of [objective techniques](#objective-personality), especially in field settings.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!reliability}\index{reliability!inter-rater}\index{personality assessment!objective}
Field [reliability](#reliability) refers to [reliability](#reliability) in actual practice rather than ideal [reliability](#reliability) in optimal conditions of a controlled lab study.\index{personality assessment!projective!scientific status}\index{reliability}
The [reliability](#reliability) and standardization of administration of the [Rorschach](#rorschach) is also questionable.\index{personality assessment!projective!scientific status}\index{standardization}\index{Rorschach Inkblot Test!reliability}
The [test–retest reliability](#testRetest-reliability) is also low—but high enough to be passable for research settings—but it should be used with caution in clinical diagnostic settings.\index{personality assessment!projective!scientific status}\index{reliability!test–retest}

### Influence of Measurement Error on Scores {#projectiveMeasurementError}

Another important consideration is the influence of [measurement error](#measurementError) on scores: one aspect of the [Rorschach](#rorschach) in particular that can lead to [measurement error](#measurementError) is the effect of response frequency on test [validity](#validity).\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!validity}\index{measurement error}
If people provide more answers, which is correlated with intelligence, these people are more likely to express a deviant answer indicative of maladjustment.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!validity}\index{measurement error}

### Validity {#projectiveValidity}

A crucial consideration of the scientific status is their [validity](#validity).\index{personality assessment!projective!scientific status}\index{validity}
[Validity](#validity) is not a yes/no thing.\index{personality assessment!projective!scientific status}\index{validity}
It is important to ask what the [validity](#validity) is for what purpose?\index{personality assessment!projective!scientific status}\index{validity}
[Rorschach](#rorschach) responses can be moderately [valid](#validity) indicators of creativity.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!validity}
Projective drawings have moderate [validity](#validity) for drawing ability.\index{personality assessment!projective!scientific status}
But are projective tests [valid](#validity) for their typical purposes in clinical psychology?\index{personality assessment!projective!scientific status}
For instance, do they have diagnostic accuracy?\index{personality assessment!projective!scientific status}
Their accuracy for their typical purposes in clinical psychology is discussed below.\index{personality assessment!projective!scientific status}

#### Criterion-Related Validity {#criterionValidity-projective}

[Criterion-related validity](#criterionValidity) would consider whether the diagnosis given on the basis of the [Rorschach](#rorschach) aligns with an external criterion of an actual diagnosis.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!validity}\index{validity!criterion}
For the [Rorschach](#rorschach), the answer is: not really.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!validity}
Scores have some relation to psychosis and thought disorders, but they are not strongly related to other aspects of psychopathology.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!validity}
Research designs comparing diagnostic versus control groups often over-estimate [predictive validity](#predictiveValidity) of the [Rorschach](#rorschach) compared to what it would be in practice because clinicians are typically interested in low [base rate](#baseRate) phenomena for which predictive accuracy will be lower.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!validity}\index{validity!predictive}\index{base rate}

#### Convergent Validity {#convergentValidity-projective}

[Convergent validity](#convergentValidity) would consider whether [Rorschach](#rorschach) findings correspond to the findings of more [reliable](#reliability) [objective](#objective-personality) tests such as the [Minnesota Multiphasic Personality Inventory](#mmpi)?\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!validity}\index{validity!convergent}\index{Minnesota Multiphasic Personality Inventory}
The answer is also no.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!validity}\index{validity!convergent}

#### Incremental Validity {#incrementalValidity-projective}

In terms of [incremental validity](#incrementalValidity), a frequent argument by proponents of projective tests is that, "I don't use the [Rorschach](#rorschach)/[TAT](#tat) in isolation but in combination with other measures."\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!validity}\index{Thematic Apperception Test}\index{validity!incremental}
But does the inclusion of the [Rorschach](#rorschach) lead to improvements in the [validity](#validity) of diagnoses of clinicians?\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!validity}\index{validity!incremental}
No.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!validity}\index{validity!incremental}
In many cases it has [*decremental* validity](#incrementalValidity)—it decreases predictive or diagnostic accuracy.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!validity}\index{validity!incremental}

#### Treatment Utility {#treatmentUtility-projective}

[Treatment utility](#treatmentUtility) considers whether it is worth the vast amount of time spent administering, scoring, and interpreting the measure (2–3 hours)?\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!utility}\index{validity!utility}
The answer is also no.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!utility}\index{validity!utility}
You can assess psychopathology more accurately with more [reliable](#reliability) and less time-consuming measures, including interviews, questionnaires, and demographic data.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!utility}\index{validity!utility}\index{reliability}
Projective measures present actual costs in addition to opportunity costs.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!utility}
Actual costs of projective measures include that they are expensive and time-consuming for training, and are time-consuming to administer, score, and interpret.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!utility}
Opportunity costs of projective measures include that it takes time away from other, more useful procedures.\index{personality assessment!projective!scientific status}\index{Rorschach Inkblot Test!utility}

### Summary {#scientificStatusSummary-projective}

Hence, I would not say the scientific status of the [Rorschach](#rorschach) is very positive.\index{personality assessment!projective!scientific status}
The evidence does not provide the evidence necessary to call projective measures "tests."\index{personality assessment!projective!scientific status}
No known projective measures have enough power to justify their lengthy use.\index{personality assessment!projective!scientific status}
Considering the important role that assessments can play in clinical decision making that influences people's lives, it seems unethical to use projective techniques, as they are currently designed and used.\index{personality assessment!projective!scientific status}\index{ethics}

## Conclusion {#conclusion-projective-personality}

Projective measures are measures in which an ambiguous stimulus is presented to the respondent, who is asked to make an open-ended response.\index{personality assessment!projective}
Projective measures were developed based on psychodynamic theory and the projective hypothesis that whatever a person does when exposed to an ambiguous stimulus will reveal important aspects of the person's personality.\index{personality assessment!projective}\index{psychoanalysis}
The goal of projective measures is to discover things that do not depend on self-knowledge and the person's ability or willingness to share it.\index{personality assessment!projective}
Projective measures aim to bypass defense mechanisms so that they assess characteristics the person has and which the person is not consciously aware of.\index{personality assessment!projective}\index{psychoanalysis!defense mechanism}
Examples of projective measures include the [Rorschach Inkblot Test](#rorschach), the [Thematic Apperception Test](#tat) (TAT), Draw-A-Person Test, and drawing a family (Kinetic Family Drawing).\index{personality assessment!projective}\index{Rorschach Inkblot Test}\index{Thematic Apperception Test}
However, there are many problems with projective measures: most projective techniques do **not** have standardized stimuli and testing instructions, systematic algorithms for scoring responses to stimuli, or well-calibrated norms for comparing responses with those of other people.\index{personality assessment!projective}\index{personality assessment!projective!scientific status}\index{standardization}\index{norm}
Their [scientific status](#projectiveScientificStatus) is not strong in terms of [utility of norms](#projectiveNorms), [reliability](#projectiveReliability), [influence of measurement error](#projectiveMeasurementError), or [validity](#projectiveValidity).\index{personality assessment!projective}\index{personality assessment!projective!scientific status}\index{norm}\index{validity}\index{reliability}\index{measurement error}
In addition, they can be very time consuming, and they provide very little information.\index{personality assessment!projective}\index{personality assessment!projective!scientific status}\index{validity!utility}
Thus, there are many reasons not to use projective measures.\index{personality assessment!projective}\index{personality assessment!projective!scientific status}\index{validity!utility}

## Suggested Readings {#readings-projective-personality}

@Lilienfeld2000
