<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Isaac T. Petersen">
<meta name="dcterms.date" content="today">
<title>21&nbsp; Computers and Adaptive Testing – Principles of Psychological Assessment: With Applied Examples in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./behavioral-assessment.html" rel="next">
<link href="./psychophysiological-measures.html" rel="prev">
<link href="./images/logo.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-d640c705e8c17715bca3574aa719063f.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-d6a2ae2cb249da1580f0a11f71b8f854.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-d640c705e8c17715bca3574aa719063f.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9be0be348ad53823ff161d1a1ef978d8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-d4727fef54d5ba1f892cea2c0407faf0.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-9be0be348ad53823ff161d1a1ef978d8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-WZJ45RB1K4"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-WZJ45RB1K4', { 'anonymize_ip': true});
</script><script type="application/json" class="js-hypothesis-config">
{
  "theme": "classic",
  "openSidebar": false,
  "showHighlights": "whenSidebarOpen"
}
</script><script async="" src="https://hypothes.is/embed.js"></script><script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script><link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta property="og:title" content="21&nbsp; Computers and Adaptive Testing – Principles of Psychological Assessment: With Applied Examples in R">
<meta property="og:description" content="">
<meta property="og:image" content="https://isaactpetersen.github.io/Principles-Psychological-Assessment/computerized-adaptive-testing_files/figure-html/fig-tcc-cat-1.png">
<meta property="og:site_name" content="Principles of Psychological Assessment: With Applied Examples in R">
<meta property="og:image:alt" content="Test Characteristic Curve.">
<meta property="og:image:height" content="960">
<meta property="og:image:width" content="1344">
<meta name="twitter:title" content="21&nbsp; Computers and Adaptive Testing – Principles of Psychological Assessment: With Applied Examples in R">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://isaactpetersen.github.io/Principles-Psychological-Assessment/computerized-adaptive-testing_files/figure-html/fig-tcc-cat-1.png">
<meta name="twitter:image:alt" content="Test Characteristic Curve.">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./computerized-adaptive-testing.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Computers and Adaptive Testing</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Principles of Psychological Assessment: With Applied Examples in R</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/isaactpetersen/Principles-Psychological-Assessment" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Part I</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scores-scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Scores and Scales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./constructs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Constructs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reliability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./validity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Validity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./generalizability-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Generalizability Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./structural-equation-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Structural Equation Modeling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./item-response-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Item Response Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Prediction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clinical-actuarial-judgment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Clinical Judgment Versus Algorithmic Prediction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clinical-assessment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">General Issues in Clinical Assessment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./evidence-based-assessment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Evidence-Based Assessment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ethics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Ethical Issues in Assessment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./factor-analysis-pca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Factor Analysis and Principal Component Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Part II</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intellectual-assessment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Intellectual Assessment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./test-bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Test Bias</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interview-dsm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The Interview and the DSM</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./objective-personality-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Objective Personality Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./projective-personality-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Projective Personality Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./psychophysiological-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Psychophysiological and Ambulatory Assessment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./computerized-adaptive-testing.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Computers and Adaptive Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./behavioral-assessment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Behavioral Assessment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./repeated-assessments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Repeated Assessments Across Time</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cognitive-assessment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Assessment of Cognition</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./diversity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Cultural and Individual Diversity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#sec-computerAssessment" id="toc-sec-computerAssessment" class="nav-link active" data-scroll-target="#sec-computerAssessment"><span class="header-section-number">21.1</span> Computer-Administered/Online Assessment</a>
  <ul>
<li><a href="#sec-computerAdvantages" id="toc-sec-computerAdvantages" class="nav-link" data-scroll-target="#sec-computerAdvantages"><span class="header-section-number">21.1.1</span> Advantages</a></li>
  <li><a href="#sec-computerValidity" id="toc-sec-computerValidity" class="nav-link" data-scroll-target="#sec-computerValidity"><span class="header-section-number">21.1.2</span> Validity Challenges</a></li>
  <li><a href="#sec-computerEthics" id="toc-sec-computerEthics" class="nav-link" data-scroll-target="#sec-computerEthics"><span class="header-section-number">21.1.3</span> Ethical Challenges</a></li>
  <li><a href="#sec-computerBestPractices" id="toc-sec-computerBestPractices" class="nav-link" data-scroll-target="#sec-computerBestPractices"><span class="header-section-number">21.1.4</span> Best Practices</a></li>
  </ul>
</li>
  <li>
<a href="#sec-adaptiveTesting" id="toc-sec-adaptiveTesting" class="nav-link" data-scroll-target="#sec-adaptiveTesting"><span class="header-section-number">21.2</span> Adaptive Testing</a>
  <ul>
<li>
<a href="#sec-adaptiveManual" id="toc-sec-adaptiveManual" class="nav-link" data-scroll-target="#sec-adaptiveManual"><span class="header-section-number">21.2.1</span> Manual Administration of Adaptive Testing (Adaptive Testing without IRT)</a>
  <ul>
<li><a href="#sec-skipRules" id="toc-sec-skipRules" class="nav-link" data-scroll-target="#sec-skipRules"><span class="header-section-number">21.2.1.1</span> Skip Rules</a></li>
  <li><a href="#sec-basalCeiling" id="toc-sec-basalCeiling" class="nav-link" data-scroll-target="#sec-basalCeiling"><span class="header-section-number">21.2.1.2</span> Basal and Ceiling Approach</a></li>
  <li>
<a href="#sec-adaptiveCountdown" id="toc-sec-adaptiveCountdown" class="nav-link" data-scroll-target="#sec-adaptiveCountdown"><span class="header-section-number">21.2.1.3</span> Countdown Approach</a>
  <ul class="collapse">
<li><a href="#sec-classificationMethod" id="toc-sec-classificationMethod" class="nav-link" data-scroll-target="#sec-classificationMethod"><span class="header-section-number">21.2.1.3.1</span> Classification Method</a></li>
  <li><a href="#sec-fses" id="toc-sec-fses" class="nav-link" data-scroll-target="#sec-fses"><span class="header-section-number">21.2.1.3.2</span> Full Scores on Elevated Scales Method</a></li>
  </ul>
</li>
  <li><a href="#sec-manualAdaptiveTestingSummary" id="toc-sec-manualAdaptiveTestingSummary" class="nav-link" data-scroll-target="#sec-manualAdaptiveTestingSummary"><span class="header-section-number">21.2.1.4</span> Summary</a></li>
  </ul>
</li>
  <li><a href="#sec-catIRT" id="toc-sec-catIRT" class="nav-link" data-scroll-target="#sec-catIRT"><span class="header-section-number">21.2.2</span> CAT with IRT</a></li>
  </ul>
</li>
  <li>
<a href="#sec-gettingStarted-cat" id="toc-sec-gettingStarted-cat" class="nav-link" data-scroll-target="#sec-gettingStarted-cat"><span class="header-section-number">21.3</span> Getting Started</a>
  <ul>
<li><a href="#sec-loadLibraries-cat" id="toc-sec-loadLibraries-cat" class="nav-link" data-scroll-target="#sec-loadLibraries-cat"><span class="header-section-number">21.3.1</span> Load Libraries</a></li>
  </ul>
</li>
  <li>
<a href="#sec-exampleUnidimensionalCAT" id="toc-sec-exampleUnidimensionalCAT" class="nav-link" data-scroll-target="#sec-exampleUnidimensionalCAT"><span class="header-section-number">21.4</span> Example of Unidimensional CAT</a>
  <ul>
<li><a href="#sec-definePopulationIRTparameters" id="toc-sec-definePopulationIRTparameters" class="nav-link" data-scroll-target="#sec-definePopulationIRTparameters"><span class="header-section-number">21.4.1</span> Define Population IRT Parameters</a></li>
  <li><a href="#sec-fitIRTmodel-cat" id="toc-sec-fitIRTmodel-cat" class="nav-link" data-scroll-target="#sec-fitIRTmodel-cat"><span class="header-section-number">21.4.2</span> Fit IRT Model</a></li>
  <li><a href="#sec-modelOutput-cat" id="toc-sec-modelOutput-cat" class="nav-link" data-scroll-target="#sec-modelOutput-cat"><span class="header-section-number">21.4.3</span> Model Summary</a></li>
  <li><a href="#sec-modelPlots-cat" id="toc-sec-modelPlots-cat" class="nav-link" data-scroll-target="#sec-modelPlots-cat"><span class="header-section-number">21.4.4</span> Model Plots</a></li>
  <li><a href="#sec-itemPlots-cat" id="toc-sec-itemPlots-cat" class="nav-link" data-scroll-target="#sec-itemPlots-cat"><span class="header-section-number">21.4.5</span> Item Plots</a></li>
  <li><a href="#sec-createMathItems-cat" id="toc-sec-createMathItems-cat" class="nav-link" data-scroll-target="#sec-createMathItems-cat"><span class="header-section-number">21.4.6</span> Create Math Items</a></li>
  <li><a href="#sec-runCAT" id="toc-sec-runCAT" class="nav-link" data-scroll-target="#sec-runCAT"><span class="header-section-number">21.4.7</span> Run Computerized Adaptive Test (CAT)</a></li>
  <li>
<a href="#sec-catResults" id="toc-sec-catResults" class="nav-link" data-scroll-target="#sec-catResults"><span class="header-section-number">21.4.8</span> CAT Results</a>
  <ul>
<li><a href="#sec-CATstandardErrors" id="toc-sec-CATstandardErrors" class="nav-link" data-scroll-target="#sec-CATstandardErrors"><span class="header-section-number">21.4.8.1</span> CAT Standard Errors</a></li>
  <li><a href="#sec-cat95CI" id="toc-sec-cat95CI" class="nav-link" data-scroll-target="#sec-cat95CI"><span class="header-section-number">21.4.8.2</span> CAT 95% Confidence Interval</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#sec-cat-preexisting" id="toc-sec-cat-preexisting" class="nav-link" data-scroll-target="#sec-cat-preexisting"><span class="header-section-number">21.5</span> Creating a Computerized Adaptive Test From an Item Response Theory Model</a>
  <ul>
<li><a href="#sec-cat-createItems" id="toc-sec-cat-createItems" class="nav-link" data-scroll-target="#sec-cat-createItems"><span class="header-section-number">21.5.1</span> Create Items</a></li>
  <li><a href="#sec-cat-runModel" id="toc-sec-cat-runModel" class="nav-link" data-scroll-target="#sec-cat-runModel"><span class="header-section-number">21.5.2</span> Run Computerized Adaptive Test</a></li>
  </ul>
</li>
  <li><a href="#sec-conclusion-cat" id="toc-sec-conclusion-cat" class="nav-link" data-scroll-target="#sec-conclusion-cat"><span class="header-section-number">21.6</span> Conclusion</a></li>
  <li><a href="#sec-readings-cat" id="toc-sec-readings-cat" class="nav-link" data-scroll-target="#sec-readings-cat"><span class="header-section-number">21.7</span> Suggested Readings</a></li>
  <li>
<a href="#sec-exercises-cat" id="toc-sec-exercises-cat" class="nav-link" data-scroll-target="#sec-exercises-cat"><span class="header-section-number">21.8</span> Exercises</a>
  <ul>
<li><a href="#sec-exercisesQuestions-cat" id="toc-sec-exercisesQuestions-cat" class="nav-link" data-scroll-target="#sec-exercisesQuestions-cat"><span class="header-section-number">21.8.1</span> Questions</a></li>
  <li><a href="#sec-exercisesAnswers-cat" id="toc-sec-exercisesAnswers-cat" class="nav-link" data-scroll-target="#sec-exercisesAnswers-cat"><span class="header-section-number">21.8.2</span> Answers</a></li>
  </ul>
</li>
  <li><a href="#sec-sessionInfo-cat" id="toc-sec-sessionInfo-cat" class="nav-link" data-scroll-target="#sec-sessionInfo-cat"><span class="header-section-number">21.9</span> Session Info</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/isaactpetersen/Principles-Psychological-Assessment/edit/main/computerized-adaptive-testing.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/isaactpetersen/Principles-Psychological-Assessment/blob/main/computerized-adaptive-testing.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/isaactpetersen/Principles-Psychological-Assessment/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><div class="alert alert-info hints-alert">
  <div class="hints-icon">
    <i class="fa fa-comments-o"></i>
  </div>
  <div class="hints-container">
    <b>I need your help!</b>
    <p>
    I want your feedback to make the book better for you and other readers. If you find typos, errors, or places where the text may be improved, please let me know.
    The best ways to provide feedback are by <a href="https://github.com/isaactpetersen/Principles-Psychological-Assessment">GitHub</a> or <a href="https://hypothes.is">hypothes.is</a> annotations.
    </p>

    <p>
      <i class="fa fa-github"></i>
      <a href="https://github.com/isaactpetersen/Principles-Psychological-Assessment/issues">Opening an issue</a> or <a href="https://github.com/isaactpetersen/Principles-Psychological-Assessment/pulls">submitting a pull request</a> on GitHub: <a href="https://github.com/isaactpetersen/Principles-Psychological-Assessment">https://github.com/isaactpetersen/Principles-Psychological-Assessment</a>
    </p>
    <p>
      <img style="display: inline;" src="https://hypothes.is/organizations/__default__/logo" alt="Hypothesis">
      Adding an annotation using <a href="https://hypothes.is">hypothes.is</a>.
      To add an annotation, <span style="background-color: #3297FD; color: white">select some text</span> and then click the
      <span class="svg-icon--inline"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewbox="0 0 16 16" class="annotator-adder-actions__icon"><path fill="currentColor" fill-rule="nonzero" d="M15 0c.27 0 .505.099.703.297A.961.961 0 0116 1v15l-4-3H1a.974.974 0 01-.703-.29A.953.953 0 010 12V1C0 .719.096.482.29.29A.966.966 0 011 0h14zM7 3l-.469.063c-.312.041-.656.187-1.031.437-.375.25-.719.646-1.031 1.188C4.156 5.229 4 6 4 7l.002.063.006.062a.896.896 0 01.008.11l-.002.074-.006.066a1.447 1.447 0 00.43 1.188C4.729 8.854 5.082 9 5.5 9c.417 0 .77-.146 1.063-.438C6.854 8.271 7 7.918 7 7.5c0-.417-.146-.77-.438-1.063A1.447 1.447 0 005.5 6c-.073 0-.146.005-.219.016-.073.01-.14.026-.203.046.177-1.03.542-1.632 1.094-1.804L7 4V3zm5 0l-.469.063c-.312.041-.656.187-1.031.437-.375.25-.719.646-1.031 1.188C9.156 5.229 9 6 9 7l.002.063.006.062a.896.896 0 01.008.11l-.002.074-.006.066a1.447 1.447 0 00.43 1.188c.291.291.645.437 1.062.437.417 0 .77-.146 1.063-.438.291-.291.437-.645.437-1.062 0-.417-.146-.77-.438-1.063A1.447 1.447 0 0010.5 6c-.073 0-.146.005-.219.016-.073.01-.14.026-.203.046.177-1.03.542-1.632 1.094-1.804L12 4V3z"></path></svg></span>
      symbol on the pop-up menu.
      To see the annotations of others, click the
      <span class="svg-icon--inline"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewbox="0 0 16 16" class=""><g fill-rule="evenodd"><rect fill="none" stroke="none" x="0" y="0" width="16" height="16"></rect><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 12L6 8l4-4"></path></g></svg></span>
      symbol in the upper right-hand corner of the page.
    </p>
  </div>
</div>

<header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-cat" class="quarto-section-identifier"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Computers and Adaptive Testing</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="sec-computerAssessment" class="level2" data-number="21.1"><h2 data-number="21.1" class="anchored" data-anchor-id="sec-computerAssessment">
<span class="header-section-number">21.1</span> Computer-Administered/Online Assessment</h2>
<p>Computer-administered and online assessments have the potential to be both desirable and dangerous <span class="citation" data-cites="Buchanan2002">(<a href="references.html#ref-Buchanan2002" role="doc-biblioref">Buchanan, 2002</a>)</span>. The potential is to have a mental health screening instrument online that a person fills out, is automatically scored, and automatic feedback is provided with suggestions to follow a particular course of action. This would save the clinician time and could lead to a more productive therapy session. As an example, I have clients complete a brief measure of behavioral issues on a tablet when they arrive and are waiting in the waiting room. This is an example of measurement-based care, in which the participant’s treatment response is assessed throughout treatment to help determine whether treatment is working or not, and whether to try something different. In addition, emerging techniques in machine learning may be useful for scoring of high-dimensional data in assessment in clinical practice <span class="citation" data-cites="GalatzerLevy2023">(<a href="references.html#ref-GalatzerLevy2023" role="doc-biblioref">Galatzer-Levy &amp; Onnela, 2023</a>)</span>.</p>
<section id="sec-computerAdvantages" class="level3" data-number="21.1.1"><h3 data-number="21.1.1" class="anchored" data-anchor-id="sec-computerAdvantages">
<span class="header-section-number">21.1.1</span> Advantages</h3>
<p>There are many advantages of computer-administered or online assessment:</p>
<ul>
<li>Computer-administered and online assessment requires less time on the part of the clinician and administrators than traditional assessment methods. They do not need the clinician to administer and score the assessment, and scores can be entered directly into the client’s chart.</li>
<li>Computer-administered and online assessments tend to be less costly than traditional assessment methods.</li>
<li>Computer-administered and online assessments can increase access to services because some people can complete the assessment who otherwise would not be able to complete it. For example, some people may be restricted by geographic or financial circumstances. You can provide the questionnaire in multiple languages and modalities, including written, spoken, and pictorial.</li>
<li>People may disclose more information to a computer than to a person. The degree of one’s perceived anonymity matters. Perceived anonymity may be especially important for information on sensitive yet important issues, such as suicidality, homicidality, abuse, neglect, criminal behavior, etc.</li>
<li>Computerized and online assessment has the potential to be more structured and the potential to do a more comprehensive and accurate assessment than an in-person interview, which tends to be less structured and more <a href="test-bias.html">biased</a> by clinical judgment <span class="citation" data-cites="Garb2007">(<a href="references.html#ref-Garb2007" role="doc-biblioref">Garb, 2007</a>)</span>.</li>
<li>Computerized and online assessment tends to provide more comprehensive information than is usually collected in practice. Structured approaches tend to ask more questions. Computers can increase the likelihood that the client answers all questions, because it can prevent clients from skipping questions. Computers can apply “branching logic” to adapt which questions are asked based on the participant’s responses (i.e., <a href="#sec-adaptiveTesting">adaptive testing</a>) to more efficiently gain greater coverage. Clinicians tend not to ask questions about important issues. Clinicians fail to examine disorders other than the hypothesized ones, which is known as diagnostic overshadowing due to the confirmation <a href="test-bias.html">bias</a> of looking for evidence-confirming information rather than disconfirming evidence. In general, computers give more diagnoses than clinicians. Clinicians often miss co-occurring disorders. Doing a more comprehensive assessment normalizes that people can and do experience the behavioral issues that they are asked about, and can increase self-disclosure. Greater structure leads to higher <a href="reliability.html#sec-interrater-reliability">inter-rater reliability</a>, less <a href="test-bias.html">bias</a>, and greater <a href="validity.html">validity</a>.</li>
<li>Computerized and online assessment lends itself to continuous monitoring during treatment for measurement-based care. Measurement-based care has been shown to be related to better treatment outcomes. Computerized or online assessment may be important in risk assessment that might otherwise go unrecognized. <a href="validity.html#sec-treatmentUtility">Treatment utility</a> of computerized assessment has been demonstrated for suicide and substance use.</li>
</ul></section><section id="sec-computerValidity" class="level3" data-number="21.1.2"><h3 data-number="21.1.2" class="anchored" data-anchor-id="sec-computerValidity">
<span class="header-section-number">21.1.2</span> Validity Challenges</h3>
<p>There are a number of challenges to the <a href="validity.html">validity</a> of computer-administered and online assessment:</p>
<ul>
<li>The impersonality of computers; however, this does not seem to be a strong threat.</li>
<li>Lack of control in the testing situation.</li>
<li>The possibility that extraneous factors can influence responses.</li>
<li>Language and cultural differences; it is difficult to ask follow-up questions to assess understanding unless a clinician is present.</li>
<li>Inability to observe the client’s body language or nonverbals.</li>
<li>Computers are not a great medium to assess constructs that could be affected by computer-related anxiety.</li>
<li>Some constructs show different ratings online versus in-person.</li>
<li>Computer-administered and online assessment may require different <a href="scores-scales.html#sec-norm">norms</a> and cutoffs than paper-and-pencil assessment. Different <a href="scores-scales.html#sec-norm">norms</a> could be necessary, for example, due to increased self-disclosure and higher ratings of negative affect in computer-administered assessment compared to in-person assessment.</li>
<li>Careless and fraudulent responding can be common when recruiting an online sample to complete a survey <span class="citation" data-cites="Chandler2020">(<a href="references.html#ref-Chandler2020" role="doc-biblioref">Chandler et al., 2020</a>)</span>. Additional steps may need to be taken to ensure high-quality responses such as CAPTCHA (or reCAPTCHA), internet protocol (IP) verification of location, and attention or <a href="validity.html">validity</a> checks.</li>
</ul>
<p>In general, online assessments of personality seem generally comparable to their paper-and-pencil versions, but their psychometric properties are not identical. In general, computer-administered and online assessments yield the same factor structure as in-person assessments, but particular items may not function in the same way across computer versus in-person assessments.</p>
</section><section id="sec-computerEthics" class="level3" data-number="21.1.3"><h3 data-number="21.1.3" class="anchored" data-anchor-id="sec-computerEthics">
<span class="header-section-number">21.1.3</span> Ethical Challenges</h3>
<p>There are important <a href="ethics.html">ethical</a> challenges of using computer-administered and online assessments:</p>
<ul>
<li>The internet and app stores provide a medium for the dissemination and proliferation of quackery. Businesses sell access to assessment information despite no evidence of the <a href="reliability.html">reliability</a> or <a href="validity.html">validity</a> of the measure.</li>
<li>When giving potentially distressing or threatening feedback, it is important to provide opportunities for follow-up sessions or counseling. When using online assessment in research, you can state that release of test scores is not possible, and that participants should consult a professional if they are worried or would like a professional assessment.</li>
<li>An additional <a href="ethics.html">ethical</a> challenge of computer-administered and online assessment deals with test security. The <a href="validity.html">validity</a> of many tests is based on the assumption that the client is not knowledgeable about the test materials. Detailed information on many protected tests is available on the internet <span class="citation" data-cites="Ruiz2002">(<a href="references.html#ref-Ruiz2002" role="doc-biblioref">Ruiz et al., 2002</a>)</span>, and it could be used by malingerers to fake health or illness.</li>
<li>Data security is another potential challenge of computer-administered and online assessments, including how to protect HIPAA compliance in the clinical context.</li>
</ul></section><section id="sec-computerBestPractices" class="level3" data-number="21.1.4"><h3 data-number="21.1.4" class="anchored" data-anchor-id="sec-computerBestPractices">
<span class="header-section-number">21.1.4</span> Best Practices</h3>
<p>Below are best practices for computer-administered and online assessments:</p>
<ul>
<li>Only use measures with established <a href="reliability.html">reliability</a> and <a href="validity.html">validity</a>, unless you are studying them, in which case you should evaluate their psychometrics.</li>
<li>Have a trained clinician review the results of the assessment.</li>
<li>Combine computer-administered assessment with clinical judgment. Clients can be expected to make errors completing the assessment, so ask necessary follow-up questions after getting results from computer-administered assessments. Asking follow-up questions can help avoid <a href="prediction.html#sec-falsePositive">false positive</a> errors in diagnosis. Check whether a client mistakenly reported something; or whether they under-/over-reported psychopathology.</li>
<li>Provide opportunities for follow-up sessions or counseling if distressing or threatening feedback is provided.</li>
<li>It may be important to correct for a person’s level of experience with computers when using computerized tasks for clinical decision-making <span class="citation" data-cites="LeeMeeuwKjoeInPress">(<a href="references.html#ref-LeeMeeuwKjoeInPress" role="doc-biblioref">Lee Meeuw Kjoe et al., 2021</a>)</span>.</li>
</ul></section></section><section id="sec-adaptiveTesting" class="level2" data-number="21.2"><h2 data-number="21.2" class="anchored" data-anchor-id="sec-adaptiveTesting">
<span class="header-section-number">21.2</span> Adaptive Testing</h2>
<p>Adaptive testing involves having the respondent complete only those items that are needed to answer an assessment question. It involves changing which items are administered based on responses to previous items, and administering only a subset of the possible items. Adaptive testing is commonly used in <a href="intellectual-assessment.html#sec-intelligence">intelligence testing</a>, <a href="intellectual-assessment.html#sec-achievementAptitude">achievement testing</a>, and <a href="intellectual-assessment.html#sec-achievementAptitude">aptitude testing</a>. Adaptive testing is not yet commonly used for <a href="objective-personality-testing.html">personality</a> or psychopathology assessment. Most approaches to assessment of <a href="objective-personality-testing.html">personality</a> and psychopathology rely on conventional testing approaches using <a href="reliability.html#sec-ctt">classical test theory</a>. But many <a href="interview-dsm.html#sec-structuredInterview">structured clinical interviews</a>, use decision rules to skip a diagnosis, module, or section if a decision rule is not met. Adaptive testing has also been used with observational assessments <span class="citation" data-cites="GranziolInPress">(e.g., <a href="references.html#ref-GranziolInPress" role="doc-biblioref">Granziol et al., 2022</a>)</span>.</p>
<p>A goal of adaptive testing is to get the most accurate estimate of a person’s level on a construct with the fewest items possible. Ideally, you would get similar results between adaptive testing and conventional testing that uses all items, when adaptive testing is done well.</p>
<p>There are multiple approaches to adaptive testing. Broadly, one class of approaches uses manual administration, whereas another class of approaches uses computerized adaptive testing (CAT) based on <a href="item-response-theory.html">item response theory</a> (IRT).</p>
<section id="sec-adaptiveManual" class="level3" data-number="21.2.1"><h3 data-number="21.2.1" class="anchored" data-anchor-id="sec-adaptiveManual">
<span class="header-section-number">21.2.1</span> Manual Administration of Adaptive Testing (Adaptive Testing without IRT)</h3>
<p>Manual administration of adaptive testing involves moving people up and down in the item difficulty according to their responses. Approaches to manual administration of adaptive testing include using skip rules, basal and ceiling criteria, and the countdown method.</p>
<section id="sec-skipRules" class="level4" data-number="21.2.1.1"><h4 data-number="21.2.1.1" class="anchored" data-anchor-id="sec-skipRules">
<span class="header-section-number">21.2.1.1</span> Skip Rules</h4>
<p>Many <a href="interview-dsm.html#sec-structuredInterview">structured clinical interviews</a>, such as the Structured Clinical Interview for DSM Disorders (SCID) and Mini-International Neuropsychiatric Interview (MINI), use decision rules to skip a diagnosis, module, or section if a decision rule is not met. The skip rules allow the interviews to be more efficient and therefore clinically practical.</p>
</section><section id="sec-basalCeiling" class="level4" data-number="21.2.1.2"><h4 data-number="21.2.1.2" class="anchored" data-anchor-id="sec-basalCeiling">
<span class="header-section-number">21.2.1.2</span> Basal and Ceiling Approach</h4>
<p>One approach to manual administration of adaptive testing involves establishing a respondent’s basal and ceiling level. The basal level is the <a href="item-response-theory.html#sec-itemDifficulty">difficulty</a> level at which the examinee answers almost all items correctly. The respondent’s ceiling level is the <a href="item-response-theory.html#sec-itemDifficulty">difficulty</a> level at which the examinee answers almost all items incorrectly. The basal and ceiling criteria set the rules for establishing the basal and ceiling level for each respondent and for when to terminate testing.</p>
<p>The goal of adaptive testing is to administer the fewest items necessary to get an accurate estimate of the person’s ability, to save time and prevent the respondent from becoming bored from too-easy items or frustrated from too-difficult items. The basal and ceiling approach starts testing at the recommended starting point for a person’s age or ability level. The examiner scores as items are administered. If the person gets too many items wrong in the beginning, the examiner moves to an earlier starting point, i.e., provides easier items, until the respondent gets most items correct, which establishes their basal level. Then, after establishing the respondent’s basal level, the examiner proceeds forward to progressively more difficult items until they reach their ceiling level, i.e., they get too many wrong in some set, which establishes their ceiling level.</p>
</section><section id="sec-adaptiveCountdown" class="level4" data-number="21.2.1.3"><h4 data-number="21.2.1.3" class="anchored" data-anchor-id="sec-adaptiveCountdown">
<span class="header-section-number">21.2.1.3</span> Countdown Approach</h4>
<p>The countdown approach of adaptive testing is a variant of the variable termination criterion approach to adaptive testing. It classifies the respondent into one of two groups—elevated or not elevated—based on whether they exceed the cutoff criterion on a given scale. The cutoff criterion is usually the raw score on the scale that corresponds to a clinical elevation.</p>
<p>Two countdown approaches include (1) the classification method and (2) the full scores on elevated scales (FSES) method. The countdown approach to adaptive testing is described by <span class="citation" data-cites="Forbey2007">Forbey &amp; Ben-Porath (<a href="references.html#ref-Forbey2007" role="doc-biblioref">2007</a>)</span>.</p>
<section id="sec-classificationMethod" class="level5" data-number="21.2.1.3.1"><h5 data-number="21.2.1.3.1" class="anchored" data-anchor-id="sec-classificationMethod">
<span class="header-section-number">21.2.1.3.1</span> Classification Method</h5>
<p>Using the classification method to the countdown approach of adaptive testing, the examiner stops administering items once elevation is either ruled in or ruled out. The classification method only tells you <em>whether</em> a client produced an elevated score on the scale. It does not tell you their actual score on that scale.</p>
</section><section id="sec-fses" class="level5" data-number="21.2.1.3.2"><h5 data-number="21.2.1.3.2" class="anchored" data-anchor-id="sec-fses">
<span class="header-section-number">21.2.1.3.2</span> Full Scores on Elevated Scales Method</h5>
<p>Using the full scores on elevated scales method to the countdown approach of adaptive testing, the examiner stops administering items only if elevation is ruled out. The approach generates a score on that scale only for people who produced an elevated score.</p>
</section></section><section id="sec-manualAdaptiveTestingSummary" class="level4" data-number="21.2.1.4"><h4 data-number="21.2.1.4" class="anchored" data-anchor-id="sec-manualAdaptiveTestingSummary">
<span class="header-section-number">21.2.1.4</span> Summary</h4>
<p>When doing manual administration with clinical scales, you see the greatest item savings when ordering items from least to most frequently endorsed (i.e., from most to least <a href="item-response-theory.html#sec-itemDifficulty">difficulty</a>) so you can rule people out faster. Ordering items in this way results in a 20–30% item savings on the <a href="objective-personality-testing.html#sec-mmpi">Minnesota Multiphasic Personality Inventory</a> (MMPI), and corresponding time savings. Comparative studies using the <a href="objective-personality-testing.html#sec-mmpi">MMPI</a> tend to show comparable results (i.e., similar <a href="validity.html">validity</a>) between the countdown adaptive method and the conventional testing method. That is, the reduction in items does not impair the <a href="validity.html">validity</a> of the adaptive scales. However, you can get even greater item savings when using an <a href="item-response-theory.html">IRT</a> approach to adaptive testing. Using <a href="item-response-theory.html">IRT</a>, you can order the administration of items differently for each participant to administer the next item that will provide the most <a href="item-response-theory.html#sec-irtReliability">information</a> (i.e., precision) for a respondent’s ability given their responses on all previous items.</p>
</section></section><section id="sec-catIRT" class="level3" data-number="21.2.2"><h3 data-number="21.2.2" class="anchored" data-anchor-id="sec-catIRT">
<span class="header-section-number">21.2.2</span> CAT with IRT</h3>
<p>Computerized adaptive testing (CAT) based on <a href="item-response-theory.html">IRT</a> is widely used in educational testing, including the Graduate Record Examination (GRE) and the Graduate Management Admission Test (GMAT), but it is not widespread in mental health measurement for two reasons: (1) it works best with large item banks; large item banks are generally unavailable for mental health constructs; and (2) mental health constructs are multidimensional and CAT using <a href="item-response-theory.html">IRT</a> has primarily been restricted to unidimensional constructs, such as math achievement. However, that is changing; there are now multidimensional <a href="item-response-theory.html">IRT</a> approaches that allow simultaneously estimating people’s scores on multiple dimensions, as described in <a href="item-response-theory.html#sec-irt-twoPLmultidimensional" class="quarto-xref"><span>Section 8.6</span></a>. For example, the higher-order construct of externalizing problems includes sub-dimensions including aggression and rule-breaking.</p>
<p>A CAT is designed to locate a person’s level on the construct (theta) with as few items as possible. CAT has potential for greater item savings than the <a href="#sec-adaptiveCountdown">countdown approach</a>, but it has more assumptions. <a href="item-response-theory.html">IRT</a> can be used to create CATs using information gleaned from the <a href="item-response-theory.html">IRT</a> model’s item parameters, including <a href="item-response-theory.html#sec-itemDiscrimination">discrimination</a> and <a href="item-response-theory.html#sec-itemDifficulty">difficulty</a> (or severity). The item’s <a href="item-response-theory.html#sec-itemDiscrimination">discrimination</a> indicates how strongly the item is related to the construct. For a strong measure, you want highly <a href="item-response-theory.html#sec-itemDiscrimination">discriminating</a> items that are strongly related to the construct. In terms of <a href="item-response-theory.html#sec-itemDifficulty">item difficulty/severity</a>, you want items that span the full distribution of <a href="item-response-theory.html#sec-itemDifficulty">difficulty/severity</a> so they are non-redundant.</p>
<p>An <a href="item-response-theory.html">IRT</a>-based CAT starts with a highly <a href="item-response-theory.html#sec-itemDiscrimination">discriminating</a> item at the 50th percentile of the distribution (<a href="item-response-theory.html#sec-itemDifficulty">severity</a>) (or at whatever level is the best estimate of the person’s ability/severity before the CAT is administered). Then, based on the participant’s response, it generates a provisional estimate of the person’s level on the construct and administers the item that will provide the most <a href="item-response-theory.html#sec-irtReliability">information</a>. For example, if the respondent gets the first item correct, the CAT administers a highly <a href="item-response-theory.html#sec-itemDiscrimination">discriminating</a> item that might be at the 75th percentile of the distribution (<a href="item-response-theory.html#sec-itemDifficulty">severity</a>). And so on, based on the participants’ responses.</p>
<p>As described in <a href="item-response-theory.html#sec-irtReliability" class="quarto-xref"><span>Section 8.1.6</span></a>, <a href="item-response-theory.html#sec-irtReliability">item information</a> is how much measurement precision for the construct is provided by a particular item. In other words, <a href="item-response-theory.html#sec-irtReliability">item information</a> indicates how much the item reduces the <a href="reliability.html#sec-standardErrorOfMeasurement">standard error of measurement</a>; i.e., how much the item reduces uncertainty of our estimate of the respondent’s construct level. An <a href="item-response-theory.html">IRT</a>-based CAT continues to generate provisional estimates of the person’s construct level and updates it based on new responses. The CAT tries to find the construct level where the respondent keeps getting items right and wrong (or endorsing versus not endorsing) 50% of the time. This process continues until the uncertainty in the person’s estimated construct level is smaller than a pre-defined threshold—that is, when we are fairly confident (to some threshold) about a person’s construct level.</p>
<p>CAT is a promising approach that saves time because it tailors which items are administered to which person and in which order based on their construct level to get the most <a href="reliability.html">reliable</a> estimate in the shortest time possible. It administers items that are appropriate to the person’s construct level, and it does not administer items that are way too easy or way too hard for the person, which saves time, boredom, and frustration. It shortens the assessment because not all items are administered, and it typically results in around 50% item savings or more. It also allows for increased measurement precision, because you are drilling down deeper (i.e., asking more items) near the person’s construct level. You can control the measurement precision of the CAT because you can specify the threshold of measurement precision (i.e., <a href="reliability.html#sec-standardErrorOfMeasurement">standard error of measurement</a>) at which testing is terminated. For example, you could have the CAT terminate when the <a href="reliability.html#sec-standardErrorOfMeasurement">standard error of measurement</a> of a person’s construct level becomes less than 0.2.</p>
<p>However, CATs assume that if you get a more difficult item correct, you would have gotten easier items correct, which might not be true in all contexts (especially for constructs that are not unidimensional). For example, just because a person does not endorse low-severity symptoms does not necessarily mean that they will not endorse higher-severity symptoms, especially when assessing a multidimensional construct.</p>
<p>Simpler CATs are built using unidimensional <a href="item-response-theory.html">IRT</a>. But many aspects of psychopathology are not unidimensional, and would violate assumptions of unidimensional <a href="item-response-theory.html">IRT</a>. For example, the externalizing spectrum includes sub-dimensions including aggression, disinhibition, and substance use. You can use multidimensional <a href="item-response-theory.html">IRT</a> to build CATs, though this is more complicated. For instance, you could estimate a <a href="factor-analysis-pca.html#sec-bifactorModel">bifactor model</a> in which each item (e.g., “hits others”) loads onto the general latent factor (e.g., externalizing problems) and its specific sub-dimension (e.g., aggression versus rule-breaking). Computerized adaptive testing of mental health disorders is reviewed by <span class="citation" data-cites="Gibbons2016">Gibbons et al. (<a href="references.html#ref-Gibbons2016" role="doc-biblioref">2016</a>)</span>.</p>
<p>Well-designed CATs show equivalent <a href="reliability.html">reliability</a> and <a href="validity.html">validity</a> to their full-scale counterparts. By contrast, many short forms are not as accurate as their full-scale counterparts. Part of the reason that CATs tend to do better than short forms is that the CATs are adaptive; they determine which items to administer based on the participant’s responses to prior items, unlike short forms. For guidelines on developing and evaluating short forms, see <span class="citation" data-cites="Smith2000">Smith et al. (<a href="references.html#ref-Smith2000" role="doc-biblioref">2000</a>)</span>.</p>
</section></section><section id="sec-gettingStarted-cat" class="level2" data-number="21.3"><h2 data-number="21.3" class="anchored" data-anchor-id="sec-gettingStarted-cat">
<span class="header-section-number">21.3</span> Getting Started</h2>
<section id="sec-loadLibraries-cat" class="level3" data-number="21.3.1"><h3 data-number="21.3.1" class="anchored" data-anchor-id="sec-loadLibraries-cat">
<span class="header-section-number">21.3.1</span> Load Libraries</h3>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">library</span>(<span class="st">"petersenlab"</span>) <span class="co">#to install: install.packages("remotes"); remotes::install_github("DevPsyLab/petersenlab")</span></span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">library</span>(<span class="st">"mirtCAT"</span>)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="fu">library</span>(<span class="st">"here"</span>)</span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="fu">library</span>(<span class="st">"tinytex"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section></section><section id="sec-exampleUnidimensionalCAT" class="level2" data-number="21.4"><h2 data-number="21.4" class="anchored" data-anchor-id="sec-exampleUnidimensionalCAT">
<span class="header-section-number">21.4</span> Example of Unidimensional CAT</h2>
<p>The computerized adaptive test (CAT) was fit using the <code>mirtCAT</code> package <span class="citation" data-cites="R-mirtCAT">(<a href="references.html#ref-R-mirtCAT" role="doc-biblioref">Chalmers, 2021</a>)</span>. The example of a CAT with unidimensional data is adapted from <code>mirtCAT</code> documentation: <a href="https://philchalmers.github.io/mirtCAT/html/unidim-exampleGUI.html" class="uri">https://philchalmers.github.io/mirtCAT/html/unidim-exampleGUI.html</a> (archived at <a href="https://perma.cc/3ZW4-DAUR" class="uri">https://perma.cc/3ZW4-DAUR</a>)</p>
<section id="sec-definePopulationIRTparameters" class="level3" data-number="21.4.1"><h3 data-number="21.4.1" class="anchored" data-anchor-id="sec-definePopulationIRTparameters">
<span class="header-section-number">21.4.1</span> Define Population IRT Parameters</h3>
<p>For reproducibility, we set the seed below. Using the same seed will yield the same answer every time. There is nothing special about this particular seed.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">set.seed</span>(<span class="dv">52242</span>)</span>
<span id="cb2-2"><a href="#cb2-2"></a>nitems <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb2-3"><a href="#cb2-3"></a>itemnames <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"Item."</span>, <span class="dv">1</span><span class="sc">:</span>nitems, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb2-4"><a href="#cb2-4"></a>a <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rlnorm</span>(nitems, <span class="at">meanlog =</span> .<span class="dv">2</span>, <span class="at">sdlog =</span> .<span class="dv">3</span>))</span>
<span id="cb2-5"><a href="#cb2-5"></a>d <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">rnorm</span>(nitems, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>))</span>
<span id="cb2-6"><a href="#cb2-6"></a>pars <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">a1 =</span> a, <span class="at">d =</span> d, <span class="at">g =</span> <span class="fl">0.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section><section id="sec-fitIRTmodel-cat" class="level3" data-number="21.4.2"><h3 data-number="21.4.2" class="anchored" data-anchor-id="sec-fitIRTmodel-cat">
<span class="header-section-number">21.4.2</span> Fit IRT Model</h3>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">generate.mirt_object</span>(pars, <span class="st">"3PL"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section><section id="sec-modelOutput-cat" class="level3" data-number="21.4.3"><h3 data-number="21.4.3" class="anchored" data-anchor-id="sec-modelOutput-cat">
<span class="header-section-number">21.4.3</span> Model Summary</h3>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>            F1    h2
Item.1   0.673 0.453
Item.2   0.369 0.136
Item.3   0.548 0.300
Item.4   0.500 0.250
Item.5   0.783 0.614
Item.6   0.579 0.335
Item.7   0.733 0.538
Item.8   0.377 0.142
Item.9   0.535 0.286
Item.10  0.503 0.253
Item.11  0.546 0.298
Item.12  0.591 0.349
Item.13  0.630 0.397
Item.14  0.597 0.356
Item.15  0.583 0.340
Item.16  0.389 0.151
Item.17  0.570 0.325
Item.18  0.460 0.211
Item.19  0.683 0.466
Item.20  0.507 0.257
Item.21  0.547 0.300
Item.22  0.581 0.337
Item.23  0.784 0.614
Item.24  0.546 0.298
Item.25  0.551 0.303
Item.26  0.615 0.379
Item.27  0.567 0.321
Item.28  0.554 0.307
Item.29  0.625 0.391
Item.30  0.733 0.537
Item.31  0.737 0.544
Item.32  0.458 0.210
Item.33  0.520 0.271
Item.34  0.575 0.331
Item.35  0.532 0.283
Item.36  0.448 0.201
Item.37  0.481 0.231
Item.38  0.485 0.236
Item.39  0.459 0.210
Item.40  0.656 0.430
Item.41  0.682 0.464
Item.42  0.596 0.355
Item.43  0.682 0.465
Item.44  0.564 0.319
Item.45  0.392 0.154
Item.46  0.538 0.290
Item.47  0.490 0.240
Item.48  0.641 0.411
Item.49  0.519 0.269
Item.50  0.505 0.255
Item.51  0.490 0.240
Item.52  0.530 0.281
Item.53  0.319 0.101
Item.54  0.834 0.695
Item.55  0.643 0.414
Item.56  0.489 0.239
Item.57  0.563 0.317
Item.58  0.538 0.289
Item.59  0.627 0.393
Item.60  0.598 0.357
Item.61  0.480 0.230
Item.62  0.523 0.273
Item.63  0.586 0.343
Item.64  0.650 0.422
Item.65  0.652 0.425
Item.66  0.723 0.522
Item.67  0.447 0.199
Item.68  0.524 0.274
Item.69  0.489 0.239
Item.70  0.783 0.613
Item.71  0.680 0.462
Item.72  0.455 0.207
Item.73  0.452 0.204
Item.74  0.614 0.377
Item.75  0.629 0.396
Item.76  0.595 0.354
Item.77  0.651 0.424
Item.78  0.515 0.265
Item.79  0.671 0.450
Item.80  0.464 0.215
Item.81  0.612 0.375
Item.82  0.491 0.241
Item.83  0.489 0.239
Item.84  0.385 0.148
Item.85  0.455 0.207
Item.86  0.402 0.161
Item.87  0.537 0.288
Item.88  0.651 0.424
Item.89  0.662 0.439
Item.90  0.433 0.188
Item.91  0.562 0.315
Item.92  0.752 0.565
Item.93  0.572 0.328
Item.94  0.518 0.269
Item.95  0.559 0.312
Item.96  0.714 0.509
Item.97  0.714 0.510
Item.98  0.591 0.349
Item.99  0.346 0.120
Item.100 0.443 0.196

SS loadings:  32.822 
Proportion Var:  0.328 

Factor correlations: 

   F1
F1  1</code></pre>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="fu">coef</span>(mod, <span class="at">simplify =</span> <span class="cn">TRUE</span>, <span class="at">IRTpars =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>$items
             a      b   g u
Item.1   1.549  0.298 0.2 1
Item.2   0.676  0.742 0.2 1
Item.3   1.115 -0.536 0.2 1
Item.4   0.982 -0.448 0.2 1
Item.5   2.145 -0.380 0.2 1
Item.6   1.208  0.409 0.2 1
Item.7   1.836 -0.606 0.2 1
Item.8   0.694  2.000 0.2 1
Item.9   1.077 -0.991 0.2 1
Item.10  0.991  0.570 0.2 1
Item.11  1.109  0.493 0.2 1
Item.12  1.246  0.363 0.2 1
Item.13  1.382 -0.417 0.2 1
Item.14  1.267  0.925 0.2 1
Item.15  1.222  0.405 0.2 1
Item.16  0.718  2.062 0.2 1
Item.17  1.182 -0.233 0.2 1
Item.18  0.881 -0.151 0.2 1
Item.19  1.591  0.647 0.2 1
Item.20  1.000 -0.120 0.2 1
Item.21  1.113 -0.430 0.2 1
Item.22  1.214 -1.437 0.2 1
Item.23  2.146 -0.025 0.2 1
Item.24  1.110  0.204 0.2 1
Item.25  1.123 -0.584 0.2 1
Item.26  1.329  0.127 0.2 1
Item.27  1.171 -0.421 0.2 1
Item.28  1.132  0.136 0.2 1
Item.29  1.363  0.425 0.2 1
Item.30  1.834  0.019 0.2 1
Item.31  1.858 -0.215 0.2 1
Item.32  0.878  1.927 0.2 1
Item.33  1.037  0.396 0.2 1
Item.34  1.197 -0.304 0.2 1
Item.35  1.069 -1.655 0.2 1
Item.36  0.853  0.979 0.2 1
Item.37  0.933  0.799 0.2 1
Item.38  0.945 -0.062 0.2 1
Item.39  0.879  1.319 0.2 1
Item.40  1.477  0.629 0.2 1
Item.41  1.585  0.136 0.2 1
Item.42  1.262  0.913 0.2 1
Item.43  1.587  0.508 0.2 1
Item.44  1.164 -1.134 0.2 1
Item.45  0.725 -0.191 0.2 1
Item.46  1.087  0.724 0.2 1
Item.47  0.957  1.837 0.2 1
Item.48  1.423  0.155 0.2 1
Item.49  1.033  0.892 0.2 1
Item.50  0.996 -0.109 0.2 1
Item.51  0.958  1.628 0.2 1
Item.52  1.063  0.368 0.2 1
Item.53  0.572 -1.014 0.2 1
Item.54  2.568  0.403 0.2 1
Item.55  1.430 -0.931 0.2 1
Item.56  0.955 -0.193 0.2 1
Item.57  1.160  0.829 0.2 1
Item.58  1.086  0.126 0.2 1
Item.59  1.371 -0.150 0.2 1
Item.60  1.269  0.220 0.2 1
Item.61  0.931  0.868 0.2 1
Item.62  1.044  0.597 0.2 1
Item.63  1.231 -0.278 0.2 1
Item.64  1.455  1.303 0.2 1
Item.65  1.464 -0.644 0.2 1
Item.66  1.780 -0.313 0.2 1
Item.67  0.850  1.466 0.2 1
Item.68  1.046 -1.062 0.2 1
Item.69  0.953  0.441 0.2 1
Item.70  2.141 -0.051 0.2 1
Item.71  1.576 -0.743 0.2 1
Item.72  0.870 -0.833 0.2 1
Item.73  0.862 -0.859 0.2 1
Item.74  1.325 -0.981 0.2 1
Item.75  1.378 -0.196 0.2 1
Item.76  1.259  0.496 0.2 1
Item.77  1.459  0.795 0.2 1
Item.78  1.021  0.834 0.2 1
Item.79  1.539 -0.290 0.2 1
Item.80  0.891  0.943 0.2 1
Item.81  1.319 -0.067 0.2 1
Item.82  0.960  1.233 0.2 1
Item.83  0.953 -1.236 0.2 1
Item.84  0.710 -1.120 0.2 1
Item.85  0.870  0.592 0.2 1
Item.86  0.746 -2.303 0.2 1
Item.87  1.082 -0.205 0.2 1
Item.88  1.460 -0.297 0.2 1
Item.89  1.505  0.138 0.2 1
Item.90  0.819  0.273 0.2 1
Item.91  1.155  0.149 0.2 1
Item.92  1.939  0.153 0.2 1
Item.93  1.188  0.856 0.2 1
Item.94  1.032 -1.256 0.2 1
Item.95  1.147  0.432 0.2 1
Item.96  1.734 -0.289 0.2 1
Item.97  1.737  0.262 0.2 1
Item.98  1.247 -0.538 0.2 1
Item.99  0.628 -0.839 0.2 1
Item.100 0.841 -0.259 0.2 1

$means
F1 
 0 

$cov
   F1
F1  1</code></pre>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>modItemParameters <span class="ot">&lt;-</span> <span class="fu">coef</span>(</span>
<span id="cb8-2"><a href="#cb8-2"></a>  mod,</span>
<span id="cb8-3"><a href="#cb8-3"></a>  <span class="at">simplify =</span> <span class="cn">TRUE</span>,</span>
<span id="cb8-4"><a href="#cb8-4"></a>  <span class="at">IRTpars =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>items</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section><section id="sec-modelPlots-cat" class="level3" data-number="21.4.4"><h3 data-number="21.4.4" class="anchored" data-anchor-id="sec-modelPlots-cat">
<span class="header-section-number">21.4.4</span> Model Plots</h3>
<p>A test characteristic curve of the measure is in <a href="#fig-tcc-cat" class="quarto-xref">Figure&nbsp;<span>21.1</span></a>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="fu">plot</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-tcc-cat" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Test Characteristic Curve.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-tcc-cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="computerized-adaptive-testing_files/figure-html/fig-tcc-cat-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;21.1: Test Characteristic Curve."><img src="computerized-adaptive-testing_files/figure-html/fig-tcc-cat-1.png" class="img-fluid figure-img" alt="Test Characteristic Curve." width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tcc-cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.1: Test Characteristic Curve.
</figcaption></figure>
</div>
</div>
</div>
<p>The test information and <a href="reliability.html#sec-standardErrorOfMeasurement">standard error of measurement</a> as a function of the person’s construct level (theta; <span class="math inline">\(\theta\)</span>) is in <a href="#fig-infoSE-cat" class="quarto-xref">Figure&nbsp;<span>21.2</span></a>. The test appears to measure theta (<span class="math inline">\(\theta\)</span>) with <span class="math inline">\(SE &lt; .4\)</span> within a range of −1.5 to 2.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">plot</span>(mod, <span class="at">type =</span> <span class="st">"infoSE"</span>, <span class="at">theta_lim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-infoSE-cat" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Test Information and Standard Error of Measurement.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-infoSE-cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="computerized-adaptive-testing_files/figure-html/fig-infoSE-cat-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;21.2: Test Information and Standard Error of Measurement."><img src="computerized-adaptive-testing_files/figure-html/fig-infoSE-cat-1.png" class="img-fluid figure-img" alt="Test Information and Standard Error of Measurement." width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-infoSE-cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.2: Test Information and Standard Error of Measurement.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="sec-itemPlots-cat" class="level3" data-number="21.4.5"><h3 data-number="21.4.5" class="anchored" data-anchor-id="sec-itemPlots-cat">
<span class="header-section-number">21.4.5</span> Item Plots</h3>
<p>Item characteristic curves are in <a href="#fig-icc-cat" class="quarto-xref">Figure&nbsp;<span>21.3</span></a>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">plot</span>(mod, <span class="at">type =</span> <span class="st">"trace"</span>, <span class="at">theta_lim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-icc-cat" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Item Characteristic Curves.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-icc-cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="computerized-adaptive-testing_files/figure-html/fig-icc-cat-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;21.3: Item Characteristic Curves."><img src="computerized-adaptive-testing_files/figure-html/fig-icc-cat-1.png" class="img-fluid figure-img" alt="Item Characteristic Curves." width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-icc-cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.3: Item Characteristic Curves.
</figcaption></figure>
</div>
</div>
</div>
<p>Item information curves are in <a href="#fig-info-cat" class="quarto-xref">Figure&nbsp;<span>21.4</span></a>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">plot</span>(mod, <span class="at">type =</span> <span class="st">"infotrace"</span>, <span class="at">theta_lim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-info-cat" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Item Information Curves.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-info-cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="computerized-adaptive-testing_files/figure-html/fig-info-cat-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;21.4: Item Information Curves."><img src="computerized-adaptive-testing_files/figure-html/fig-info-cat-1.png" class="img-fluid figure-img" alt="Item Information Curves." width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-info-cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.4: Item Information Curves.
</figcaption></figure>
</div>
</div>
</div>
<ul>
<li>Item 30 would be a good starting item; it has a difficulty closest to the 50th percentile <span class="math inline">\((b = 0.019)\)</span> and a high discrimination <span class="math inline">\((a = 1.834)\)</span>.</li>
<li>Item 70 would be a good starting item; it has a difficulty closest to the 50th percentile <span class="math inline">\((b = -0.051)\)</span> and a high discrimination <span class="math inline">\((a = 2.141)\)</span>.</li>
<li>Item 86 is an easy item <span class="math inline">\((b = -2.303)\)</span>.</li>
<li>Item 16 is a difficult item <span class="math inline">\((b = 2.062)\)</span>.</li>
<li>Item 53 has a low discrimination <span class="math inline">\((a = 0.572)\)</span>.</li>
</ul>
<p>Item characteristic curves and information curves for these items are in Figures <a href="#fig-catICCItem30" class="quarto-xref"><span>21.5</span></a>–<a href="#fig-catICCItem53" class="quarto-xref"><span>21.9</span></a>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="fu">itemplot</span>(<span class="at">object =</span> mod, <span class="at">item =</span> <span class="st">"Item.30"</span>, <span class="st">"infotrace"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-catICCItem30" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Item Characteristic Curves and Information Curves: Item 30.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-catICCItem30-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="computerized-adaptive-testing_files/figure-html/fig-catICCItem30-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;21.5: Item Characteristic Curves and Information Curves: Item 30."><img src="computerized-adaptive-testing_files/figure-html/fig-catICCItem30-1.png" class="img-fluid figure-img" alt="Item Characteristic Curves and Information Curves: Item 30." width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catICCItem30-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.5: Item Characteristic Curves and Information Curves: Item 30.
</figcaption></figure>
</div>
</div>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">itemplot</span>(<span class="at">object =</span> mod, <span class="at">item =</span> <span class="st">"Item.70"</span>, <span class="st">"infotrace"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-catICCItem70" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Item Characteristic Curves and Information Curves: Item 70.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-catICCItem70-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="computerized-adaptive-testing_files/figure-html/fig-catICCItem70-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;21.6: Item Characteristic Curves and Information Curves: Item 70."><img src="computerized-adaptive-testing_files/figure-html/fig-catICCItem70-1.png" class="img-fluid figure-img" alt="Item Characteristic Curves and Information Curves: Item 70." width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catICCItem70-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.6: Item Characteristic Curves and Information Curves: Item 70.
</figcaption></figure>
</div>
</div>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="fu">itemplot</span>(<span class="at">object =</span> mod, <span class="at">item =</span> <span class="st">"Item.86"</span>, <span class="st">"infotrace"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-catICCItem86" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Item Characteristic Curves and Information Curves: Item 86.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-catICCItem86-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="computerized-adaptive-testing_files/figure-html/fig-catICCItem86-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;21.7: Item Characteristic Curves and Information Curves: Item 86."><img src="computerized-adaptive-testing_files/figure-html/fig-catICCItem86-1.png" class="img-fluid figure-img" alt="Item Characteristic Curves and Information Curves: Item 86." width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catICCItem86-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.7: Item Characteristic Curves and Information Curves: Item 86.
</figcaption></figure>
</div>
</div>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="fu">itemplot</span>(<span class="at">object =</span> mod, <span class="at">item =</span> <span class="st">"Item.16"</span>, <span class="st">"infotrace"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-catICCItem16" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Item Characteristic Curves and Information Curves: Item 16.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-catICCItem16-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="computerized-adaptive-testing_files/figure-html/fig-catICCItem16-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;21.8: Item Characteristic Curves and Information Curves: Item 16."><img src="computerized-adaptive-testing_files/figure-html/fig-catICCItem16-1.png" class="img-fluid figure-img" alt="Item Characteristic Curves and Information Curves: Item 16." width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catICCItem16-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.8: Item Characteristic Curves and Information Curves: Item 16.
</figcaption></figure>
</div>
</div>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="fu">itemplot</span>(<span class="at">object =</span> mod, <span class="at">item =</span> <span class="st">"Item.53"</span>, <span class="st">"infotrace"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-catICCItem53" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Item Characteristic Curves and Information Curves: Item 53.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-catICCItem53-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="computerized-adaptive-testing_files/figure-html/fig-catICCItem53-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure&nbsp;21.9: Item Characteristic Curves and Information Curves: Item 53."><img src="computerized-adaptive-testing_files/figure-html/fig-catICCItem53-1.png" class="img-fluid figure-img" alt="Item Characteristic Curves and Information Curves: Item 53." width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catICCItem53-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.9: Item Characteristic Curves and Information Curves: Item 53.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="sec-createMathItems-cat" class="level3" data-number="21.4.6"><h3 data-number="21.4.6" class="anchored" data-anchor-id="sec-createMathItems-cat">
<span class="header-section-number">21.4.6</span> Create Math Items</h3>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>questions <span class="ot">&lt;-</span> answers <span class="ot">&lt;-</span> <span class="fu">character</span>(nitems)</span>
<span id="cb18-2"><a href="#cb18-2"></a>choices <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="st">"a"</span>, nitems, <span class="dv">5</span>)</span>
<span id="cb18-3"><a href="#cb18-3"></a>spacing <span class="ot">&lt;-</span> <span class="fu">floor</span>(d <span class="sc">-</span> <span class="fu">min</span>(d)) <span class="sc">+</span> <span class="dv">1</span> <span class="co">#easier items have more variation</span></span>
<span id="cb18-4"><a href="#cb18-4"></a></span>
<span id="cb18-5"><a href="#cb18-5"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nitems){</span>
<span id="cb18-6"><a href="#cb18-6"></a>  n1 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb18-7"><a href="#cb18-7"></a>  n2 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">101</span><span class="sc">:</span><span class="dv">200</span>, <span class="dv">1</span>)</span>
<span id="cb18-8"><a href="#cb18-8"></a>  ans <span class="ot">&lt;-</span> n1 <span class="sc">+</span> n2</span>
<span id="cb18-9"><a href="#cb18-9"></a>  questions[i] <span class="ot">&lt;-</span> <span class="fu">paste</span>(n1, <span class="st">" + "</span>, n2, <span class="st">" = ?"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span>
<span id="cb18-10"><a href="#cb18-10"></a>  answers[i] <span class="ot">&lt;-</span> <span class="fu">as.character</span>(ans)</span>
<span id="cb18-11"><a href="#cb18-11"></a>  ch <span class="ot">&lt;-</span> ans <span class="sc">+</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span><span class="sc">:-</span><span class="dv">1</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) <span class="sc">*</span> spacing[i,], <span class="dv">5</span>)</span>
<span id="cb18-12"><a href="#cb18-12"></a>  ch[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1</span>)] <span class="ot">&lt;-</span> ans</span>
<span id="cb18-13"><a href="#cb18-13"></a>  choices[i,] <span class="ot">&lt;-</span> <span class="fu">as.character</span>(ch)</span>
<span id="cb18-14"><a href="#cb18-14"></a>}</span>
<span id="cb18-15"><a href="#cb18-15"></a></span>
<span id="cb18-16"><a href="#cb18-16"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-17"><a href="#cb18-17"></a>  <span class="at">Questions =</span> questions,</span>
<span id="cb18-18"><a href="#cb18-18"></a>  <span class="at">Answer =</span> answers,</span>
<span id="cb18-19"><a href="#cb18-19"></a>  <span class="at">Option =</span> choices,</span>
<span id="cb18-20"><a href="#cb18-20"></a>  <span class="at">Type =</span> <span class="st">"radio"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section><section id="sec-runCAT" class="level3" data-number="21.4.7"><h3 data-number="21.4.7" class="anchored" data-anchor-id="sec-runCAT">
<span class="header-section-number">21.4.7</span> Run Computerized Adaptive Test (CAT)</h3>
<p>Set the minimum <a href="reliability.html#sec-standardErrorOfMeasurement">standard error of measurement</a> for the latent trait (theta; <span class="math inline">\(\theta\)</span>) that must be reached before stopping the CAT. You can lengthen the CAT by lowering the minimum <a href="reliability.html#sec-standardErrorOfMeasurement">standard error of measurement</a>, or you can shorten the CAT by raising the minimum <a href="reliability.html#sec-standardErrorOfMeasurement">standard error of measurement</a>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a>minimum_SEM <span class="ot">&lt;-</span> .<span class="dv">3</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Run the CAT and stop once the <a href="reliability.html#sec-standardErrorOfMeasurement">standard error of measurement</a> for the latent trait (theta; <span class="math inline">\(\theta\)</span>) becomes <span class="math inline">\(0.3\)</span> or lower.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>result <span class="ot">&lt;-</span> <span class="fu">mirtCAT</span>(</span>
<span id="cb20-2"><a href="#cb20-2"></a>  df,</span>
<span id="cb20-3"><a href="#cb20-3"></a>  mod,</span>
<span id="cb20-4"><a href="#cb20-4"></a>  <span class="at">start_item =</span> <span class="st">"MI"</span>,</span>
<span id="cb20-5"><a href="#cb20-5"></a>  <span class="at">method =</span> <span class="st">"EAP"</span>,</span>
<span id="cb20-6"><a href="#cb20-6"></a>  <span class="at">criteria =</span> <span class="st">"MI"</span>,</span>
<span id="cb20-7"><a href="#cb20-7"></a>  <span class="at">design =</span> <span class="fu">list</span>(<span class="at">min_SEM =</span> minimum_SEM))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="fu">RNGkind</span>(<span class="st">"default"</span>, <span class="st">"default"</span>, <span class="st">"default"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section><section id="sec-catResults" class="level3" data-number="21.4.8"><h3 data-number="21.4.8" class="anchored" data-anchor-id="sec-catResults">
<span class="header-section-number">21.4.8</span> CAT Results</h3>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="fu">print</span>(result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code> n.items.answered  Theta_1 SE.Theta_1
               27 0.238911  0.2975387</code></pre>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="fu">summary</span>(result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>$final_estimates
            Theta_1
Estimates 0.2389110
SEs       0.2975387

$raw_responses
 [1] "230" "170" "167" "177" "175" "216" "177" "218" "184" "191" "184" "202"
[13] "294" "204" "200" "204" "264" "242" "177" "189" "267" "200" "235" "149"
[25] "248" "180" "239"

$scored_responses
 [1] 1 1 1 1 0 1 0 1 1 1 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1

$items_answered
 [1] 70 54 92 19 43 23 97 30  1 41 40 31 89  5 66 96 48 79  7 88 75 59 13 26 71
[26] 81 29

$thetas_history
        Theta_1
 [1,] 0.0000000
 [2,] 0.4056545
 [3,] 0.7815060
 [4,] 0.9750919
 [5,] 1.1561966
 [6,] 0.7421218
 [7,] 0.8464452
 [8,] 0.5304194
 [9,] 0.6256858
[10,] 0.7128811
[11,] 0.7809691
[12,] 0.6338431
[13,] 0.6792420
[14,] 0.5228702
[15,] 0.5589624
[16,] 0.3679772
[17,] 0.4110162
[18,] 0.3112852
[19,] 0.3505818
[20,] 0.1782808
[21,] 0.2190867
[22,] 0.2576467
[23,] 0.1698955
[24,] 0.2023291
[25,] 0.1355895
[26,] 0.1602090
[27,] 0.1960021
[28,] 0.2389110

$thetas_SE_history
        Theta_1
 [1,] 1.0000000
 [2,] 0.9069127
 [3,] 0.8093285
 [4,] 0.7266039
 [5,] 0.6878798
 [6,] 0.6098350
 [7,] 0.5592082
 [8,] 0.5192925
 [9,] 0.4820574
[10,] 0.4630971
[11,] 0.4487481
[12,] 0.4224150
[13,] 0.4079867
[14,] 0.3918681
[15,] 0.3778294
[16,] 0.3693179
[17,] 0.3568027
[18,] 0.3507425
[19,] 0.3408871
[20,] 0.3437896
[21,] 0.3332037
[22,] 0.3252183
[23,] 0.3240032
[24,] 0.3164469
[25,] 0.3147717
[26,] 0.3076080
[27,] 0.3017742
[28,] 0.2975387

$terminated_sucessfully
[1] TRUE</code></pre>
</div>
</div>
<section id="sec-CATstandardErrors" class="level4" data-number="21.4.8.1"><h4 data-number="21.4.8.1" class="anchored" data-anchor-id="sec-CATstandardErrors">
<span class="header-section-number">21.4.8.1</span> CAT Standard Errors</h4>
<p><a href="reliability.html#sec-standardErrorOfMeasurement">Standard errors of measurement</a> of a person’s estimated construct level (theta; <span class="math inline">\(\theta\)</span>) as a function of the item (presented in the order that items were administered as part of the CAT) are in <a href="#fig-standardError-cat" class="quarto-xref">Figure&nbsp;<span>21.10</span></a>.</p>
<p>Initially, the respondent got the first items correct, which raised the estimate of their construct level. However, as the respondent got more items incorrect, the CAT converged upon the estimate that the person has a construct level around <span class="math inline">\(theta = 0.24\)</span>, which means that the person scored slightly above average (i.e., 0.24 standard deviations above the mean).</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">plot</span>(result, <span class="at">SE =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-standardError-cat" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Standard Errors of Measurement Around Theta in a Computerized Adaptive Test.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-standardError-cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="computerized-adaptive-testing_files/figure-html/fig-standardError-cat-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure&nbsp;21.10: Standard Errors of Measurement Around Theta in a Computerized Adaptive Test."><img src="computerized-adaptive-testing_files/figure-html/fig-standardError-cat-1.png" class="img-fluid figure-img" alt="Standard Errors of Measurement Around Theta in a Computerized Adaptive Test." width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-standardError-cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.10: Standard Errors of Measurement Around Theta in a Computerized Adaptive Test.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="sec-cat95CI" class="level4" data-number="21.4.8.2"><h4 data-number="21.4.8.2" class="anchored" data-anchor-id="sec-cat95CI">
<span class="header-section-number">21.4.8.2</span> CAT 95% Confidence Interval</h4>
<p>95% confidence intervals of a person’s estimated construct level (theta; <span class="math inline">\(\theta\)</span>) as a function of the item (presented in the order that items were administered as part of the CAT) are in Figure <a href="#fig-cat95PctCI" class="quarto-xref">Figure&nbsp;<span>21.11</span></a>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="fu">plot</span>(result, <span class="at">SE =</span> <span class="fu">qnorm</span>(.<span class="dv">975</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-cat95PctCI" class="quarto-float quarto-figure quarto-figure-center anchored" alt="95% Confidence Interval of Theta in a Computerized Adaptive Test.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-cat95PctCI-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="computerized-adaptive-testing_files/figure-html/fig-cat95PctCI-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figure&nbsp;21.11: 95% Confidence Interval of Theta in a Computerized Adaptive Test."><img src="computerized-adaptive-testing_files/figure-html/fig-cat95PctCI-1.png" class="img-fluid figure-img" alt="95% Confidence Interval of Theta in a Computerized Adaptive Test." width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cat95PctCI-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.11: 95% Confidence Interval of Theta in a Computerized Adaptive Test.
</figcaption></figure>
</div>
</div>
</div>
</section></section></section><section id="sec-cat-preexisting" class="level2" data-number="21.5"><h2 data-number="21.5" class="anchored" data-anchor-id="sec-cat-preexisting">
<span class="header-section-number">21.5</span> Creating a Computerized Adaptive Test From an Item Response Theory Model</h2>
<p>You can create a computerized adaptive test from any <a href="item-response-theory.html">item response theory</a> model.</p>
<section id="sec-cat-createItems" class="level3" data-number="21.5.1"><h3 data-number="21.5.1" class="anchored" data-anchor-id="sec-cat-createItems">
<span class="header-section-number">21.5.1</span> Create Items</h3>
<p>For instance, below we create a matrix with the questions and response options from the <a href="item-response-theory.html#sec-irt-gradedResponseModel">graded response model</a> that we fit in <a href="item-response-theory.html#sec-irt-gradedResponseModel" class="quarto-xref"><span>Section 8.9</span></a> in Chapter <a href="item-response-theory.html" class="quarto-xref"><span>Chapter 8</span></a> on <a href="item-response-theory.html">item response theory</a>.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a>numItemsGRM <span class="ot">&lt;-</span> <span class="fu">nrow</span>(<span class="fu">coef</span>(</span>
<span id="cb28-2"><a href="#cb28-2"></a>  gradedResponseModel,</span>
<span id="cb28-3"><a href="#cb28-3"></a>  <span class="at">simplify =</span> <span class="cn">TRUE</span>,</span>
<span id="cb28-4"><a href="#cb28-4"></a>  <span class="at">IRTpars =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>items)</span>
<span id="cb28-5"><a href="#cb28-5"></a></span>
<span id="cb28-6"><a href="#cb28-6"></a><span class="fu">names</span>(Science)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] "Comfort" "Work"    "Future"  "Benefit"</code></pre>
</div>
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a>questionsGRM <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb30-2"><a href="#cb30-2"></a>  <span class="st">"Science and technology are making our lives healthier, easier and more comfortable."</span>,</span>
<span id="cb30-3"><a href="#cb30-3"></a>  <span class="st">"The application of science and new technology will make work more interesting."</span>,</span>
<span id="cb30-4"><a href="#cb30-4"></a>  <span class="st">"Thanks to science and technology, there will be more opportunities for the future generations."</span>,</span>
<span id="cb30-5"><a href="#cb30-5"></a>  <span class="st">"The benefits of science are greater than any harmful effect it may have."</span></span>
<span id="cb30-6"><a href="#cb30-6"></a>)</span>
<span id="cb30-7"><a href="#cb30-7"></a></span>
<span id="cb30-8"><a href="#cb30-8"></a>responseOptionsGRM <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb30-9"><a href="#cb30-9"></a>  <span class="st">"strongly disagree"</span>,</span>
<span id="cb30-10"><a href="#cb30-10"></a>  <span class="st">"disagree to some extent"</span>,</span>
<span id="cb30-11"><a href="#cb30-11"></a>  <span class="st">"agree to some extent"</span>,</span>
<span id="cb30-12"><a href="#cb30-12"></a>  <span class="st">"strongly agree"</span></span>
<span id="cb30-13"><a href="#cb30-13"></a>)</span>
<span id="cb30-14"><a href="#cb30-14"></a></span>
<span id="cb30-15"><a href="#cb30-15"></a>numResponseOptionsGRM <span class="ot">&lt;-</span> <span class="fu">length</span>(responseOptionsGRM)</span>
<span id="cb30-16"><a href="#cb30-16"></a></span>
<span id="cb30-17"><a href="#cb30-17"></a>choicesGRM <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="st">"a"</span>, numItemsGRM, numResponseOptionsGRM)</span>
<span id="cb30-18"><a href="#cb30-18"></a></span>
<span id="cb30-19"><a href="#cb30-19"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>numItemsGRM){</span>
<span id="cb30-20"><a href="#cb30-20"></a>  choicesGRM[i,] <span class="ot">&lt;-</span> responseOptionsGRM</span>
<span id="cb30-21"><a href="#cb30-21"></a>}</span>
<span id="cb30-22"><a href="#cb30-22"></a></span>
<span id="cb30-23"><a href="#cb30-23"></a>dfGRM <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb30-24"><a href="#cb30-24"></a>  <span class="at">Questions =</span> questionsGRM,</span>
<span id="cb30-25"><a href="#cb30-25"></a>  <span class="at">Option =</span> choicesGRM,</span>
<span id="cb30-26"><a href="#cb30-26"></a>  <span class="at">Type =</span> <span class="st">"radio"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section><section id="sec-cat-runModel" class="level3" data-number="21.5.2"><h3 data-number="21.5.2" class="anchored" data-anchor-id="sec-cat-runModel">
<span class="header-section-number">21.5.2</span> Run Computerized Adaptive Test</h3>
<p>Then you can create and run the computerized adaptive model:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a>resultGRM <span class="ot">&lt;-</span> <span class="fu">mirtCAT</span>(</span>
<span id="cb31-2"><a href="#cb31-2"></a>  dfGRM,</span>
<span id="cb31-3"><a href="#cb31-3"></a>  gradedResponseModel,</span>
<span id="cb31-4"><a href="#cb31-4"></a>  <span class="at">start_item =</span> <span class="st">"MI"</span>,</span>
<span id="cb31-5"><a href="#cb31-5"></a>  <span class="at">method =</span> <span class="st">"EAP"</span>,</span>
<span id="cb31-6"><a href="#cb31-6"></a>  <span class="at">criteria =</span> <span class="st">"MI"</span>,</span>
<span id="cb31-7"><a href="#cb31-7"></a>  <span class="at">design =</span> <span class="fu">list</span>(<span class="at">min_SEM =</span> minimum_SEM))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section></section><section id="sec-conclusion-cat" class="level2" data-number="21.6"><h2 data-number="21.6" class="anchored" data-anchor-id="sec-conclusion-cat">
<span class="header-section-number">21.6</span> Conclusion</h2>
<p>Computer-administered and online assessments have the potential to be both desirable and dangerous. They have key <a href="#sec-computerAdvantages">advantages</a>; at the same time, they have both <a href="#sec-computerValidity">validity</a> and <a href="#sec-computerEthics">ethical</a> challenges. <a href="#sec-computerBestPractices">Best practices</a> for computer-administered and online assessments are provided. <a href="#sec-adaptiveTesting">Adaptive testing</a> involves having the respondent complete only those items that are needed to answer an assessment question, which can save immense time without sacrificing <a href="validity.html">validity</a> (if done well). There are many approaches to <a href="#sec-adaptiveTesting">adaptive testing</a>, including <a href="#sec-adaptiveManual">manual administration</a>—such as <a href="#sec-skipRules">skip rules</a>, <a href="#sec-basalCeiling">basal and ceiling criteria</a>, and the <a href="#sec-adaptiveCountdown">countdown approach</a>—and <a href="#sec-catIRT">computerized adaptive testing (CAT) using item response theory</a>. A <a href="#sec-catIRT">CAT</a> is designed to locate a person’s level on the construct with as few items as possible. A <a href="#sec-catIRT">CAT</a> administers the items that will provide the most <a href="item-response-theory.html#sec-irtReliability">information</a> based on participants’ previous responses. <a href="#sec-catIRT">CAT</a> typically results in the greatest item savings—around 50% item savings or more.</p>
</section><section id="sec-readings-cat" class="level2" data-number="21.7"><h2 data-number="21.7" class="anchored" data-anchor-id="sec-readings-cat">
<span class="header-section-number">21.7</span> Suggested Readings</h2>
<p><span class="citation" data-cites="Buchanan2002">Buchanan (<a href="references.html#ref-Buchanan2002" role="doc-biblioref">2002</a>)</span>; <span class="citation" data-cites="Gibbons2016">Gibbons et al. (<a href="references.html#ref-Gibbons2016" role="doc-biblioref">2016</a>)</span></p>
</section><section id="sec-exercises-cat" class="level2" data-number="21.8"><h2 data-number="21.8" class="anchored" data-anchor-id="sec-exercises-cat">
<span class="header-section-number">21.8</span> Exercises</h2>
<section id="sec-exercisesQuestions-cat" class="level3" data-number="21.8.1"><h3 data-number="21.8.1" class="anchored" data-anchor-id="sec-exercisesQuestions-cat">
<span class="header-section-number">21.8.1</span> Questions</h3>
</section><section id="sec-exercisesAnswers-cat" class="level3" data-number="21.8.2"><h3 data-number="21.8.2" class="anchored" data-anchor-id="sec-exercisesAnswers-cat">
<span class="header-section-number">21.8.2</span> Answers</h3>
</section></section><section id="sec-sessionInfo-cat" class="level2" data-number="21.9"><h2 data-number="21.9" class="anchored" data-anchor-id="sec-sessionInfo-cat">
<span class="header-section-number">21.9</span> Session Info</h2>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="fu">sessionInfo</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>R version 4.5.2 (2025-10-31)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 24.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: UTC
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] MOTE_1.2.2        tinytex_0.58      here_1.0.2        mirtCAT_1.14     
[5] shiny_1.12.1      mirt_1.45.1       lattice_0.22-7    petersenlab_1.2.2

loaded via a namespace (and not attached):
  [1] Rdpack_2.6.4         DBI_1.2.3            mnormt_2.1.1        
  [4] deldir_2.0-4         pbapply_1.7-4        gridExtra_2.3       
  [7] permute_0.9-8        testthat_3.3.1       rlang_1.1.7         
 [10] magrittr_2.0.4       otel_0.2.0           compiler_4.5.2      
 [13] mgcv_1.9-3           png_0.1-8            vctrs_0.6.5         
 [16] reshape2_1.4.5       quadprog_1.5-8       stringr_1.6.0       
 [19] pkgconfig_2.0.3      fastmap_1.2.0        backports_1.5.0     
 [22] pbivnorm_0.6.0       promises_1.5.0       rmarkdown_2.30      
 [25] sessioninfo_1.2.3    nloptr_2.2.1         purrr_1.2.1         
 [28] xfun_0.55            jsonlite_2.0.0       later_1.4.5         
 [31] jpeg_0.1-11          Deriv_4.2.0          psych_2.5.6         
 [34] parallel_4.5.2       lavaan_0.6-21        cluster_2.1.8.1     
 [37] R6_2.6.1             stringi_1.8.7        RColorBrewer_1.1-3  
 [40] parallelly_1.46.1    boot_1.3-32          rpart_4.1.24        
 [43] brio_1.1.5           Rcpp_1.1.1           knitr_1.51          
 [46] future.apply_1.20.1  audio_0.1-12         base64enc_0.1-3     
 [49] R.utils_2.13.0       httpuv_1.6.16        Matrix_1.7-4        
 [52] splines_4.5.2        nnet_7.3-20          tidyselect_1.2.1    
 [55] rstudioapi_0.17.1    yaml_2.3.12          vegan_2.7-2         
 [58] codetools_0.2-20     dcurver_0.9.3        listenv_0.10.0      
 [61] tibble_3.3.0         plyr_1.8.9           S7_0.2.1            
 [64] evaluate_1.0.5       foreign_0.8-90       future_1.68.0       
 [67] lpSolve_5.6.23       pillar_1.11.1        checkmate_2.3.3     
 [70] reformulas_0.4.3.1   generics_0.1.4       rprojroot_2.1.1     
 [73] mix_1.0-13           ggplot2_4.0.1        scales_1.4.0        
 [76] minqa_1.2.8          globals_0.18.0       xtable_1.8-4        
 [79] glue_1.8.0           clipr_0.8.0          Hmisc_5.2-5         
 [82] tools_4.5.2          interp_1.1-6         data.table_1.18.0   
 [85] lme4_1.1-38          beepr_2.0            SimDesign_2.22      
 [88] mvtnorm_1.3-3        grid_4.5.2           mitools_2.4         
 [91] rbibutils_2.4        latticeExtra_0.6-31  colorspace_2.1-2    
 [94] nlme_3.1-168         htmlTable_2.4.3      Formula_1.2-5       
 [97] cli_3.6.5            viridisLite_0.4.2    dplyr_1.1.4         
[100] gtable_0.3.6         R.methodsS3_1.8.2    digest_0.6.39       
[103] progressr_0.18.0     GPArotation_2025.3-1 htmlwidgets_1.6.4   
[106] farver_2.1.2         htmltools_0.5.9      R.oo_1.27.1         
[109] lifecycle_1.0.5      mime_0.13            MASS_7.3-65         </code></pre>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-Buchanan2002" class="csl-entry" role="listitem">
Buchanan, T. (2002). Online assessment: Desirable or dangerous? <em>Professional Psychology: Research and Practice</em>, <em>33</em>(2), 148–154. <a href="https://doi.org/10.1037/0735-7028.33.2.148">https://doi.org/10.1037/0735-7028.33.2.148</a>
</div>
<div id="ref-R-mirtCAT" class="csl-entry" role="listitem">
Chalmers, P. (2021). <em><span class="nocase">mirtCAT</span>: Computerized adaptive testing with multidimensional item response theory</em>. <a href="https://CRAN.R-project.org/package=mirtCAT">https://CRAN.R-project.org/package=mirtCAT</a>
</div>
<div id="ref-Chandler2020" class="csl-entry" role="listitem">
Chandler, J., Sisso, I., &amp; Shapiro, D. (2020). Participant carelessness and fraud: Consequences for clinical research and potential solutions. <em>Journal of Abnormal Psychology</em>, <em>129</em>(1), 49–55. <a href="https://doi.org/10.1037/abn0000479">https://doi.org/10.1037/abn0000479</a>
</div>
<div id="ref-Forbey2007" class="csl-entry" role="listitem">
Forbey, J. D., &amp; Ben-Porath, Y. S. (2007). Computerized adaptive personality testing: A review and illustration with the MMPI-2 computerized adaptive version. <em>Psychological Assessment</em>, <em>19</em>(1), 14–24. <a href="https://doi.org/10.1037/1040-3590.19.1.14">https://doi.org/10.1037/1040-3590.19.1.14</a>
</div>
<div id="ref-GalatzerLevy2023" class="csl-entry" role="listitem">
Galatzer-Levy, I. R., &amp; Onnela, J.-P. (2023). Machine learning and the digital measurement of psychological health. <em>Annual Review of Clinical Psychology</em>, <em>19</em>, 133–154. <a href="https://doi.org/10.1146/annurev-clinpsy-080921-073212">https://doi.org/10.1146/annurev-clinpsy-080921-073212</a>
</div>
<div id="ref-Garb2007" class="csl-entry" role="listitem">
Garb, H. N. (2007). Computer-administered interviews and rating scales. <em>Psychological Assessment</em>, <em>19</em>(1), 4–13. <a href="https://doi.org/10.1037/1040-3590.19.1.4">https://doi.org/10.1037/1040-3590.19.1.4</a>
</div>
<div id="ref-Gibbons2016" class="csl-entry" role="listitem">
Gibbons, R. D., Weiss, D. J., Frank, E., &amp; Kupfer, D. (2016). Computerized adaptive diagnosis and testing of mental health disorders. <em>Annual Review of Clinical Psychology</em>, <em>12</em>(1), 83–104. <a href="https://doi.org/10.1146/annurev-clinpsy-021815-093634">https://doi.org/10.1146/annurev-clinpsy-021815-093634</a>
</div>
<div id="ref-GranziolInPress" class="csl-entry" role="listitem">
Granziol, U., Brancaccio, A., Pizziconi, G., Spangaro, M., Gentili, F., Bosia, M., Gregori, E., Luperini, C., Pavan, C., Santarelli, V., Cavallaro, R., Cremonese, C., Favaro, A., Rossi, A., Vidotto, G., &amp; Spoto, A. (2022). On the implementation of computerized adaptive observations for psychological assessment. <em>Assessment</em>, <em>29</em>(2), 225–241. <a href="https://doi.org/10.1177/1073191120960215">https://doi.org/10.1177/1073191120960215</a>
</div>
<div id="ref-LeeMeeuwKjoeInPress" class="csl-entry" role="listitem">
Lee Meeuw Kjoe, P. R., Agelink van Rentergem, J. A., Vermeulen, I. E., &amp; Schagen, S. B. (2021). How to correct for computer experience in online cognitive testing? <em>Assessment</em>, <em>28</em>(5), 1247–1255. <a href="https://doi.org/10.1177/1073191120911098">https://doi.org/10.1177/1073191120911098</a>
</div>
<div id="ref-Ruiz2002" class="csl-entry" role="listitem">
Ruiz, M. A., Drake, E. B., Glass, A., Marcotte, D., &amp; Gorp, W. G. van. (2002). Trying to beat the system: Misuse of the internet to assist in avoiding the detection of psychological symptom dissimulation. <em>Professional Psychology: Research and Practice</em>, <em>33</em>(3), 294–299. <a href="https://doi.org/10.1037/0735-7028.33.3.294">https://doi.org/10.1037/0735-7028.33.3.294</a>
</div>
<div id="ref-Smith2000" class="csl-entry" role="listitem">
Smith, G. T., McCarthy, D. M., &amp; Anderson, K. G. (2000). On the sins of short-form development. <em>Psychological Assessment</em>, <em>12</em>(1), 102–111. <a href="https://doi.org/10.1037/1040-3590.12.1.102">https://doi.org/10.1037/1040-3590.12.1.102</a>
</div>
</div>
</section></main><!-- /main --><h2>Feedback</h2>

<div class="feedback">
    Please consider providing feedback about this textbook, so that I can make it as helpful as possible. You can provide feedback at the following link:
    
    <a href="https://forms.gle/95iW4p47cuaphTek6">https://forms.gle/95iW4p47cuaphTek6</a>
</div>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/isaactpetersen\.github\.io\/Principles-Psychological-Assessment");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><input type="hidden" id="giscus-base-theme" value="light"><input type="hidden" id="giscus-alt-theme" value="dark"><script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      if (authorPrefersDark) {
          [baseTheme, altTheme] = [altTheme, baseTheme];
      }
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "isaactpetersen/Principles-Psychological-Assessment";
    script.dataset.repoId = "MDEwOlJlcG9zaXRvcnkzNzIwMjExNjg=";
    script.dataset.category = "Chapter Comments";
    script.dataset.categoryId = "DIC_kwDOFiyXsM4CzZAv";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "0";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./psychophysiological-measures.html" class="pagination-link" aria-label="Psychophysiological and Ambulatory Assessment">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Psychophysiological and Ambulatory Assessment</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./behavioral-assessment.html" class="pagination-link" aria-label="Behavioral Assessment">
        <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Behavioral Assessment</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>“Principles of Psychological Assessment: With Applied Examples in R” was written by <a href="https://psychology.uiowa.edu/people/isaac-petersen">Isaac T. Petersen</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/isaactpetersen/Principles-Psychological-Assessment/edit/main/computerized-adaptive-testing.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/isaactpetersen/Principles-Psychological-Assessment/blob/main/computerized-adaptive-testing.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/isaactpetersen/Principles-Psychological-Assessment/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


</body></html>